# General API MCP server — generated by mcpify. Do not hand-edit.

# trixie (Debian 13), not bookworm: fastembed/ort's downloaded prebuilt
# ONNX Runtime static libs reference glibc >= 2.38 symbols (e.g.
# `__isoc23_strtoll`) that bookworm's glibc 2.36 doesn't have, which fails
# at link time. The runtime stage below must match this glibc version too,
# since the final binary is linked against it.
FROM rust:1-slim-trixie AS builder
WORKDIR /app

# rusqlite's "bundled" feature compiles vendored SQLite (and sqlite-vec) from
# source, which needs a C toolchain — `rust:*-slim` doesn't ship one by
# default the way the full `rust:*` image does.
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY Cargo.toml Cargo.lock* ./
COPY src ./src
# Every version's `.db`, not just the default `mcp_store.db` — `store.rs`'s
# `VERSION_STORE_BYTES` embeds all of them via `include_bytes!`, so
# `cargo build` fails below if any are missing from the build context.
COPY mcp_store.db ./mcp_store.db
COPY mcp_store_vincident-4.2.6.db ./mcp_store_vincident-4.2.6.db
COPY mcp_store_vknowledge-base-before-explorer-migration.db ./mcp_store_vknowledge-base-before-explorer-migration.db
COPY mcp_store_vknowledge-base-after-explorer-migration.db ./mcp_store_vknowledge-base-after-explorer-migration.db
COPY mcp_store_vknowledgebase-graphql-1.0.0.db ./mcp_store_vknowledgebase-graphql-1.0.0.db
COPY mcp_store_vreservations-2.0.0.db ./mcp_store_vreservations-2.0.0.db
COPY mcp_store_vservices-1.3.7.db ./mcp_store_vservices-1.3.7.db
COPY mcp_store_vchange-1.4.0.db ./mcp_store_vchange-1.4.0.db
COPY mcp_store_vassets-1.91.1.db ./mcp_store_vassets-1.91.1.db
COPY mcp_store_voperations-management-1.10.0.db ./mcp_store_voperations-management-1.10.0.db
COPY mcp_store_vvisitors-2.0.0.db ./mcp_store_vvisitors-2.0.0.db
COPY mcp_store_vsupporting-files-2.7.11.db ./mcp_store_vsupporting-files-2.7.11.db
COPY mcp_store_vaccess-roles-saas.db ./mcp_store_vaccess-roles-saas.db
COPY mcp_store_vaccess-roles-va-release-1-2026.db ./mcp_store_vaccess-roles-va-release-1-2026.db
COPY mcp_store_vlookandfeel-1.0.0.db ./mcp_store_vlookandfeel-1.0.0.db
COPY mcp_store_vtask-notifications-1.0.0.db ./mcp_store_vtask-notifications-1.0.0.db
COPY mcp_store_vsettings-1.1.0.db ./mcp_store_vsettings-1.1.0.db
COPY mcp_store_vcustom-action-support-saas.db ./mcp_store_vcustom-action-support-saas.db
COPY mcp_store_vcustom-action-support-va-release-1-2023-or-newer.db ./mcp_store_vcustom-action-support-va-release-1-2023-or-newer.db

RUN cargo build --release

# mcp_store.db leaves the Rust generator with an empty semantic_endpoints
# table (vectors are computed here, not by mcpify itself — see the plan's
# embeddings decision), so it must be populated before the image is usable.
RUN ./target/release/topdesk-mcp-populate-embeddings

# `fastembed`/`ort` (Story R6) may dynamically link an ONNX Runtime shared
# library rather than statically linking it — if `cargo build --release`
# above succeeds but the binary fails at runtime with a missing
# `libonnxruntime.so`, this runtime stage needs an explicit
# `COPY --from=builder` of that library (or a system package providing it).
# Flagged here for verification once R6 lands `services/embedding_service.rs`
# and this Dockerfile gets a real end-to-end build.
FROM debian:trixie-slim AS runtime
WORKDIR /app
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/topdesk-mcp ./topdesk-mcp
COPY --from=builder /app/target/release/topdesk-mcp-healthcheck ./topdesk-mcp-healthcheck
COPY --from=builder /app/mcp_store.db ./mcp_store.db

HEALTHCHECK --interval=30s --timeout=5s --retries=3 CMD ["./topdesk-mcp-healthcheck"]

ENTRYPOINT ["./topdesk-mcp"]
