// Hand-authored — MCP prompts capability. Not generated by mcpify; a
// regeneration will not touch this file, but see
// docs/mcp-prompts-workflow-plan.md before running one.
//
// Protocol-level `prompts/list`/`prompts/get` tests, kept out of
// `src/core/mcp_server.rs`'s existing `#[cfg(test)]` module entirely —
// that module stays scoped to `search`/`get`/`call`. Mirrors the
// `tokio::io::duplex` + minimal `ClientHandler` pattern that module's
// own `mcp_protocol_routes_search_get_and_call_requests` test uses,
// promoted to its own top-level integration test file per this repo's
// `tests/cli_smoke.rs` convention.

use std::sync::Arc;

use rmcp::model::{ContentBlock, GetPromptRequestParams};
use rmcp::{ServiceExt, service::RunningService};
use tokio::sync::Mutex;

use topdesk_mcp::auth::auth_manager::AuthManager;
use topdesk_mcp::core::config_schema::{AuthMethod, Config};
use topdesk_mcp::core::mcp_server::McpifyServer;

#[derive(Debug, Clone, Default)]
struct TestClient;

impl rmcp::ClientHandler for TestClient {}

fn server_with_api_version(api_version: &str) -> McpifyServer {
    let config: Config = serde_json::from_value(serde_json::json!({
        "url": "https://api.example.test",
        "auth_method": "basic"
    }))
    .unwrap();
    McpifyServer::new(
        api_version.to_string(),
        config,
        Arc::new(Mutex::new(AuthManager::new(AuthMethod::Basic))),
    )
}

async fn connected_client(
    server: McpifyServer,
) -> (
    RunningService<rmcp::RoleClient, TestClient>,
    tokio::task::JoinHandle<anyhow::Result<()>>,
) {
    let (server_transport, client_transport) = tokio::io::duplex(64 * 1024);
    let server_task = tokio::spawn(async move {
        server.serve(server_transport).await?.waiting().await?;
        anyhow::Ok(())
    });
    let client = TestClient.serve(client_transport).await.unwrap();
    (client, server_task)
}

fn prompt_text(result: &rmcp::model::GetPromptResult) -> &str {
    match &result
        .messages
        .first()
        .expect("at least one message")
        .content
    {
        ContentBlock::Text(text_content) => text_content.text.as_str(),
        other => panic!("expected text content, got {other:?}"),
    }
}

const DOMAIN_PROMPT_NAMES: [&str; 10] = [
    "topdesk-access-roles-assignment",
    "topdesk-asset-management-basics",
    "topdesk-change-management-lifecycle",
    "topdesk-incident-lifecycle",
    "topdesk-knowledge-base-lifecycle",
    "topdesk-operations-management-tasks",
    "topdesk-reference-data-lookup",
    "topdesk-reservations-booking",
    "topdesk-self-service-portal-requests",
    "topdesk-visitor-registration",
];

#[tokio::test]
async fn prompts_list_advertises_the_expected_names_and_arguments() {
    let (client, server_task) = connected_client(server_with_api_version("change-1.4.0")).await;

    let prompts = client.list_all_prompts().await.unwrap();
    let mut names: Vec<&str> = prompts.iter().map(|p| p.name.as_str()).collect();
    names.sort_unstable();
    let mut expected: Vec<&str> = DOMAIN_PROMPT_NAMES.to_vec();
    expected.push("topdesk-menu");
    expected.sort_unstable();
    assert_eq!(names, expected);

    // Every domain prompt advertises the shared optional `context` argument.
    for name in DOMAIN_PROMPT_NAMES {
        let prompt = prompts.iter().find(|p| p.name == name).unwrap();
        let arguments = prompt
            .arguments
            .as_ref()
            .unwrap_or_else(|| panic!("{name} should advertise arguments"));
        let context_arg = arguments
            .iter()
            .find(|a| a.name == "context")
            .unwrap_or_else(|| panic!("{name} should advertise a context argument"));
        assert_eq!(context_arg.required, Some(false));
    }

    // The menu takes no arguments at all.
    let menu_prompt = prompts.iter().find(|p| p.name == "topdesk-menu").unwrap();
    assert!(menu_prompt.arguments.is_none() || menu_prompt.arguments.as_ref().unwrap().is_empty());

    drop(client);
    tokio::time::timeout(std::time::Duration::from_secs(2), server_task)
        .await
        .unwrap()
        .unwrap()
        .unwrap();
}

#[tokio::test]
async fn every_domain_prompt_renders_successfully_with_its_matching_catalog() {
    let catalogs: [(&str, &str); 9] = [
        ("topdesk-incident-lifecycle", "incident-4.2.6"),
        ("topdesk-change-management-lifecycle", "change-1.4.0"),
        ("topdesk-asset-management-basics", "assets-1.91.1"),
        (
            "topdesk-knowledge-base-lifecycle",
            "knowledge-base-after-explorer-migration",
        ),
        ("topdesk-reservations-booking", "reservations-2.0.0"),
        ("topdesk-reference-data-lookup", "supporting-files-2.7.11"),
        ("topdesk-visitor-registration", "visitors-2.0.0"),
        (
            "topdesk-operations-management-tasks",
            "operations-management-1.10.0",
        ),
        ("topdesk-access-roles-assignment", "access-roles-saas"),
    ];

    for (prompt_name, matching_catalog) in catalogs {
        let (client, server_task) =
            connected_client(server_with_api_version(matching_catalog)).await;
        let result = client
            .get_prompt(GetPromptRequestParams::new(prompt_name))
            .await
            .unwrap();
        let text = prompt_text(&result);
        assert!(
            text.contains("Active catalog check\n") && !text.contains("MISMATCH"),
            "{prompt_name} should report a matching catalog, got:\n{text}"
        );

        drop(client);
        tokio::time::timeout(std::time::Duration::from_secs(2), server_task)
            .await
            .unwrap()
            .unwrap()
            .unwrap();
    }
}

#[tokio::test]
async fn self_service_portal_requests_accepts_any_of_its_three_catalogs_and_flags_others() {
    for matching_catalog in ["incident-4.2.6", "change-1.4.0", "reservations-2.0.0"] {
        let (client, server_task) =
            connected_client(server_with_api_version(matching_catalog)).await;
        let result = client
            .get_prompt(GetPromptRequestParams::new(
                "topdesk-self-service-portal-requests",
            ))
            .await
            .unwrap();
        let text = prompt_text(&result);
        assert!(
            text.contains("Active catalog check\n") && !text.contains("MISMATCH"),
            "topdesk-self-service-portal-requests should accept {matching_catalog}, got:\n{text}"
        );

        drop(client);
        tokio::time::timeout(std::time::Duration::from_secs(2), server_task)
            .await
            .unwrap()
            .unwrap()
            .unwrap();
    }

    // A catalog outside the three-way "any of" list is still a mismatch.
    let (client, server_task) = connected_client(server_with_api_version("assets-1.91.1")).await;
    let result = client
        .get_prompt(GetPromptRequestParams::new(
            "topdesk-self-service-portal-requests",
        ))
        .await
        .unwrap();
    let text = prompt_text(&result);
    assert!(text.contains("MISMATCH"));
    assert!(text.contains("restart"));

    drop(client);
    tokio::time::timeout(std::time::Duration::from_secs(2), server_task)
        .await
        .unwrap()
        .unwrap()
        .unwrap();
}

#[tokio::test]
async fn topdesk_menu_renders_active_catalog_and_lists_known_prompts() {
    let (client, server_task) = connected_client(server_with_api_version("change-1.4.0")).await;

    let result = client
        .get_prompt(GetPromptRequestParams::new("topdesk-menu"))
        .await
        .unwrap();
    let text = prompt_text(&result);
    assert!(text.contains("change-1.4.0"));
    for name in DOMAIN_PROMPT_NAMES {
        assert!(text.contains(name), "menu should mention {name}");
    }

    drop(client);
    tokio::time::timeout(std::time::Duration::from_secs(2), server_task)
        .await
        .unwrap()
        .unwrap()
        .unwrap();
}

#[tokio::test]
async fn change_management_lifecycle_echoes_supplied_context_and_handles_omitted_context() {
    let (client, server_task) = connected_client(server_with_api_version("change-1.4.0")).await;

    let with_context = client
        .get_prompt(
            GetPromptRequestParams::new("topdesk-change-management-lifecycle").with_arguments(
                serde_json::json!({ "context": "change CHG-123 already drafted" })
                    .as_object()
                    .unwrap()
                    .clone(),
            ),
        )
        .await
        .unwrap();
    let with_context_text = prompt_text(&with_context);
    assert!(with_context_text.contains("Context already provided"));
    assert!(with_context_text.contains("change CHG-123 already drafted"));

    // Partial/absent-arguments case: no `arguments` object at all.
    let without_context = client
        .get_prompt(GetPromptRequestParams::new(
            "topdesk-change-management-lifecycle",
        ))
        .await
        .unwrap();
    let without_context_text = prompt_text(&without_context);
    assert!(!without_context_text.contains("Context already provided"));
    assert!(without_context_text.contains("Approval gate"));

    drop(client);
    tokio::time::timeout(std::time::Duration::from_secs(2), server_task)
        .await
        .unwrap()
        .unwrap()
        .unwrap();
}

#[tokio::test]
async fn change_management_lifecycle_flags_a_catalog_mismatch() {
    let (client, server_task) = connected_client(server_with_api_version("general-1.2.0")).await;

    let result = client
        .get_prompt(GetPromptRequestParams::new(
            "topdesk-change-management-lifecycle",
        ))
        .await
        .unwrap();
    let text = prompt_text(&result);
    assert!(text.contains("MISMATCH"));
    assert!(text.contains("restart"));

    drop(client);
    tokio::time::timeout(std::time::Duration::from_secs(2), server_task)
        .await
        .unwrap()
        .unwrap()
        .unwrap();
}
