// General API MCP server — generated by mcpify. Do not hand-edit.
//
// jsonschema-based input/output validation. Schemas themselves are NOT
// embedded directly in this file's logic — they're loaded from a
// per-version co-located generated_schemas(_v<label>).json.zst asset
// (written directly by the Rust generator, not templated, keeping this
// file's size independent of how many operations the source spec
// declares) via `include_bytes!` per known version, so each is baked into
// the compiled binary rather than read from disk at runtime. Because of
// that, a project rebuild (`cargo build`) is required after `mcpify
// add-version` for a new version's schemas to actually take effect here.
//
// The asset is zstd-compressed: every operation's schema embeds a full
// copy of the spec's `$defs` library (a deliberate generator tradeoff —
// see `mcpify`'s `openapi::schema_resolve` — simpler than cross-schema
// `$ref` resolution, at the cost of file size), and a long-distance-
// matching compressor collapses that duplication (measured ~190 MB down
// to tens of KB on a real spec) without requiring any change to the JSON
// Schema shape itself. Decompressed once per version, lazily, into the
// same cache below.

use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

use serde::Deserialize;
use serde_json::Value;

use crate::core::errors::McpifyError;

#[derive(Debug, Deserialize)]
struct OperationSchemas {
    #[serde(rename = "inputSchema")]
    input_schema: Value,
    #[serde(rename = "outputSchema")]
    output_schema: Value,
}

// mcpify:versions:begin
fn schemas_zst_for(api_version: &str) -> Option<&'static [u8]> {
    match api_version {
        "general-1.2.0" => Some(include_bytes!("generated_schemas.json.zst")),
        "general-1.1.1" => Some(include_bytes!("generated_schemas_vgeneral-1.1.1.json.zst")),
        "general-1.1.0" => Some(include_bytes!("generated_schemas_vgeneral-1.1.0.json.zst")),
        "general-1.0.0" => Some(include_bytes!("generated_schemas_vgeneral-1.0.0.json.zst")),
        "incident-4.2.6" => Some(include_bytes!("generated_schemas_vincident-4.2.6.json.zst")),
        "incident-4.2.5" => Some(include_bytes!("generated_schemas_vincident-4.2.5.json.zst")),
        "incident-4.2.4" => Some(include_bytes!("generated_schemas_vincident-4.2.4.json.zst")),
        "incident-4.2.3" => Some(include_bytes!("generated_schemas_vincident-4.2.3.json.zst")),
        "incident-4.2.2" => Some(include_bytes!("generated_schemas_vincident-4.2.2.json.zst")),
        "incident-4.2.1" => Some(include_bytes!("generated_schemas_vincident-4.2.1.json.zst")),
        "incident-4.2.0" => Some(include_bytes!("generated_schemas_vincident-4.2.0.json.zst")),
        "incident-4.1.0" => Some(include_bytes!("generated_schemas_vincident-4.1.0.json.zst")),
        "incident-4.0.0" => Some(include_bytes!("generated_schemas_vincident-4.0.0.json.zst")),
        "incident-3.9.1" => Some(include_bytes!("generated_schemas_vincident-3.9.1.json.zst")),
        "incident-3.9.0" => Some(include_bytes!("generated_schemas_vincident-3.9.0.json.zst")),
        "incident-3.8.5" => Some(include_bytes!("generated_schemas_vincident-3.8.5.json.zst")),
        "incident-3.8.4" => Some(include_bytes!("generated_schemas_vincident-3.8.4.json.zst")),
        "incident-3.8.3" => Some(include_bytes!("generated_schemas_vincident-3.8.3.json.zst")),
        "incident-3.8.2" => Some(include_bytes!("generated_schemas_vincident-3.8.2.json.zst")),
        "incident-3.8.1" => Some(include_bytes!("generated_schemas_vincident-3.8.1.json.zst")),
        "incident-3.8.0" => Some(include_bytes!("generated_schemas_vincident-3.8.0.json.zst")),
        "incident-3.7.1" => Some(include_bytes!("generated_schemas_vincident-3.7.1.json.zst")),
        "knowledge-base-before-explorer-migration" => Some(include_bytes!(
            "generated_schemas_vknowledge-base-before-explorer-migration.json.zst"
        )),
        "knowledge-base-after-explorer-migration" => Some(include_bytes!(
            "generated_schemas_vknowledge-base-after-explorer-migration.json.zst"
        )),
        "knowledgebase-graphql-1.0.0" => Some(include_bytes!(
            "generated_schemas_vknowledgebase-graphql-1.0.0.json.zst"
        )),
        "reservations-2.0.0" => Some(include_bytes!(
            "generated_schemas_vreservations-2.0.0.json.zst"
        )),
        "reservations-1.23.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.23.0.json.zst"
        )),
        "reservations-1.22.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.22.0.json.zst"
        )),
        "reservations-1.21.1" => Some(include_bytes!(
            "generated_schemas_vreservations-1.21.1.json.zst"
        )),
        "reservations-1.21.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.21.0.json.zst"
        )),
        "reservations-1.20.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.20.0.json.zst"
        )),
        "reservations-1.19.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.19.0.json.zst"
        )),
        "reservations-1.18.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.18.0.json.zst"
        )),
        "reservations-1.17.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.17.0.json.zst"
        )),
        "reservations-1.16.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.16.0.json.zst"
        )),
        "reservations-1.15.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.15.0.json.zst"
        )),
        "reservations-1.14.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.14.0.json.zst"
        )),
        "reservations-1.13.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.13.0.json.zst"
        )),
        "reservations-1.12.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.12.0.json.zst"
        )),
        "reservations-1.11.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.11.0.json.zst"
        )),
        "reservations-1.10.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.10.0.json.zst"
        )),
        "reservations-1.9.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.9.0.json.zst"
        )),
        "reservations-1.8.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.8.0.json.zst"
        )),
        "reservations-1.7.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.7.0.json.zst"
        )),
        "reservations-1.6.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.6.0.json.zst"
        )),
        "reservations-1.5.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.5.0.json.zst"
        )),
        "reservations-1.4.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.4.0.json.zst"
        )),
        "reservations-1.3.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.3.0.json.zst"
        )),
        "reservations-1.2.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.2.0.json.zst"
        )),
        "reservations-1.1.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.1.0.json.zst"
        )),
        "reservations-1.0.0" => Some(include_bytes!(
            "generated_schemas_vreservations-1.0.0.json.zst"
        )),
        "services-1.3.7" => Some(include_bytes!("generated_schemas_vservices-1.3.7.json.zst")),
        "services-1.3.6" => Some(include_bytes!("generated_schemas_vservices-1.3.6.json.zst")),
        "services-1.3.5" => Some(include_bytes!("generated_schemas_vservices-1.3.5.json.zst")),
        "services-1.3.4" => Some(include_bytes!("generated_schemas_vservices-1.3.4.json.zst")),
        "services-1.3.3" => Some(include_bytes!("generated_schemas_vservices-1.3.3.json.zst")),
        "services-1.3.2" => Some(include_bytes!("generated_schemas_vservices-1.3.2.json.zst")),
        "services-1.3.1" => Some(include_bytes!("generated_schemas_vservices-1.3.1.json.zst")),
        "services-1.3.0" => Some(include_bytes!("generated_schemas_vservices-1.3.0.json.zst")),
        "services-1.2.0" => Some(include_bytes!("generated_schemas_vservices-1.2.0.json.zst")),
        "services-1.1.0" => Some(include_bytes!("generated_schemas_vservices-1.1.0.json.zst")),
        "services-1.0.0" => Some(include_bytes!("generated_schemas_vservices-1.0.0.json.zst")),
        "change-1.4.0" => Some(include_bytes!("generated_schemas_vchange-1.4.0.json.zst")),
        "change-1.3.7" => Some(include_bytes!("generated_schemas_vchange-1.3.7.json.zst")),
        "change-1.3.6" => Some(include_bytes!("generated_schemas_vchange-1.3.6.json.zst")),
        "change-1.3.5" => Some(include_bytes!("generated_schemas_vchange-1.3.5.json.zst")),
        "change-1.3.4" => Some(include_bytes!("generated_schemas_vchange-1.3.4.json.zst")),
        "change-1.3.3" => Some(include_bytes!("generated_schemas_vchange-1.3.3.json.zst")),
        "change-1.3.2" => Some(include_bytes!("generated_schemas_vchange-1.3.2.json.zst")),
        "change-1.3.1" => Some(include_bytes!("generated_schemas_vchange-1.3.1.json.zst")),
        "change-1.3.0" => Some(include_bytes!("generated_schemas_vchange-1.3.0.json.zst")),
        "change-1.2.5" => Some(include_bytes!("generated_schemas_vchange-1.2.5.json.zst")),
        "change-1.2.4" => Some(include_bytes!("generated_schemas_vchange-1.2.4.json.zst")),
        "change-1.2.3" => Some(include_bytes!("generated_schemas_vchange-1.2.3.json.zst")),
        "change-1.2.2" => Some(include_bytes!("generated_schemas_vchange-1.2.2.json.zst")),
        "change-1.2.1" => Some(include_bytes!("generated_schemas_vchange-1.2.1.json.zst")),
        "change-1.2.0" => Some(include_bytes!("generated_schemas_vchange-1.2.0.json.zst")),
        "change-1.1.4" => Some(include_bytes!("generated_schemas_vchange-1.1.4.json.zst")),
        "change-1.1.3" => Some(include_bytes!("generated_schemas_vchange-1.1.3.json.zst")),
        "change-1.1.2" => Some(include_bytes!("generated_schemas_vchange-1.1.2.json.zst")),
        "change-1.1.1" => Some(include_bytes!("generated_schemas_vchange-1.1.1.json.zst")),
        "change-1.1.0" => Some(include_bytes!("generated_schemas_vchange-1.1.0.json.zst")),
        "change-1.0.2" => Some(include_bytes!("generated_schemas_vchange-1.0.2.json.zst")),
        "change-1.0.1" => Some(include_bytes!("generated_schemas_vchange-1.0.1.json.zst")),
        "change-1.0.0" => Some(include_bytes!("generated_schemas_vchange-1.0.0.json.zst")),
        "assets-1.91.1" => Some(include_bytes!("generated_schemas_vassets-1.91.1.json.zst")),
        "assets-1.91.0" => Some(include_bytes!("generated_schemas_vassets-1.91.0.json.zst")),
        "assets-1.90.0" => Some(include_bytes!("generated_schemas_vassets-1.90.0.json.zst")),
        "assets-1.89.0" => Some(include_bytes!("generated_schemas_vassets-1.89.0.json.zst")),
        "assets-1.88.0" => Some(include_bytes!("generated_schemas_vassets-1.88.0.json.zst")),
        "assets-1.87.0" => Some(include_bytes!("generated_schemas_vassets-1.87.0.json.zst")),
        "assets-1.86.0" => Some(include_bytes!("generated_schemas_vassets-1.86.0.json.zst")),
        "assets-1.85.0" => Some(include_bytes!("generated_schemas_vassets-1.85.0.json.zst")),
        "assets-1.84.0" => Some(include_bytes!("generated_schemas_vassets-1.84.0.json.zst")),
        "assets-1.83.0" => Some(include_bytes!("generated_schemas_vassets-1.83.0.json.zst")),
        "assets-1.82.0" => Some(include_bytes!("generated_schemas_vassets-1.82.0.json.zst")),
        "assets-1.81.5" => Some(include_bytes!("generated_schemas_vassets-1.81.5.json.zst")),
        "assets-1.81.4" => Some(include_bytes!("generated_schemas_vassets-1.81.4.json.zst")),
        "assets-1.81.3" => Some(include_bytes!("generated_schemas_vassets-1.81.3.json.zst")),
        "assets-1.81.2" => Some(include_bytes!("generated_schemas_vassets-1.81.2.json.zst")),
        "assets-1.81.1" => Some(include_bytes!("generated_schemas_vassets-1.81.1.json.zst")),
        "assets-1.81.0" => Some(include_bytes!("generated_schemas_vassets-1.81.0.json.zst")),
        "assets-1.80.0" => Some(include_bytes!("generated_schemas_vassets-1.80.0.json.zst")),
        "assets-1.79.1" => Some(include_bytes!("generated_schemas_vassets-1.79.1.json.zst")),
        "assets-1.79.0" => Some(include_bytes!("generated_schemas_vassets-1.79.0.json.zst")),
        "assets-1.78.0" => Some(include_bytes!("generated_schemas_vassets-1.78.0.json.zst")),
        "assets-1.77.0" => Some(include_bytes!("generated_schemas_vassets-1.77.0.json.zst")),
        "assets-1.76.0" => Some(include_bytes!("generated_schemas_vassets-1.76.0.json.zst")),
        "assets-1.75.0" => Some(include_bytes!("generated_schemas_vassets-1.75.0.json.zst")),
        "assets-1.74.0" => Some(include_bytes!("generated_schemas_vassets-1.74.0.json.zst")),
        "assets-1.73.0" => Some(include_bytes!("generated_schemas_vassets-1.73.0.json.zst")),
        "assets-1.72.0" => Some(include_bytes!("generated_schemas_vassets-1.72.0.json.zst")),
        "assets-1.71.0" => Some(include_bytes!("generated_schemas_vassets-1.71.0.json.zst")),
        "assets-1.70.0" => Some(include_bytes!("generated_schemas_vassets-1.70.0.json.zst")),
        "assets-1.69.0" => Some(include_bytes!("generated_schemas_vassets-1.69.0.json.zst")),
        "assets-1.68.0" => Some(include_bytes!("generated_schemas_vassets-1.68.0.json.zst")),
        "assets-1.67.1" => Some(include_bytes!("generated_schemas_vassets-1.67.1.json.zst")),
        "assets-1.67.0" => Some(include_bytes!("generated_schemas_vassets-1.67.0.json.zst")),
        "assets-1.66.0" => Some(include_bytes!("generated_schemas_vassets-1.66.0.json.zst")),
        "assets-1.65.0" => Some(include_bytes!("generated_schemas_vassets-1.65.0.json.zst")),
        "assets-1.64.0" => Some(include_bytes!("generated_schemas_vassets-1.64.0.json.zst")),
        "assets-1.63.2" => Some(include_bytes!("generated_schemas_vassets-1.63.2.json.zst")),
        "assets-1.63.1" => Some(include_bytes!("generated_schemas_vassets-1.63.1.json.zst")),
        "assets-1.63.0" => Some(include_bytes!("generated_schemas_vassets-1.63.0.json.zst")),
        "assets-1.62.0" => Some(include_bytes!("generated_schemas_vassets-1.62.0.json.zst")),
        "assets-1.61.0" => Some(include_bytes!("generated_schemas_vassets-1.61.0.json.zst")),
        "assets-1.60.0" => Some(include_bytes!("generated_schemas_vassets-1.60.0.json.zst")),
        "assets-1.59.1" => Some(include_bytes!("generated_schemas_vassets-1.59.1.json.zst")),
        "assets-1.59.0" => Some(include_bytes!("generated_schemas_vassets-1.59.0.json.zst")),
        "assets-1.58.0" => Some(include_bytes!("generated_schemas_vassets-1.58.0.json.zst")),
        "assets-1.57.0" => Some(include_bytes!("generated_schemas_vassets-1.57.0.json.zst")),
        "assets-1.56.0" => Some(include_bytes!("generated_schemas_vassets-1.56.0.json.zst")),
        "assets-1.55.0" => Some(include_bytes!("generated_schemas_vassets-1.55.0.json.zst")),
        "assets-1.54.0" => Some(include_bytes!("generated_schemas_vassets-1.54.0.json.zst")),
        "assets-1.53.0" => Some(include_bytes!("generated_schemas_vassets-1.53.0.json.zst")),
        "assets-1.52.1" => Some(include_bytes!("generated_schemas_vassets-1.52.1.json.zst")),
        "assets-1.52.0" => Some(include_bytes!("generated_schemas_vassets-1.52.0.json.zst")),
        "assets-1.51.3" => Some(include_bytes!("generated_schemas_vassets-1.51.3.json.zst")),
        "assets-1.51.2" => Some(include_bytes!("generated_schemas_vassets-1.51.2.json.zst")),
        "assets-1.51.1" => Some(include_bytes!("generated_schemas_vassets-1.51.1.json.zst")),
        "assets-1.51.0" => Some(include_bytes!("generated_schemas_vassets-1.51.0.json.zst")),
        "assets-1.50.1" => Some(include_bytes!("generated_schemas_vassets-1.50.1.json.zst")),
        "assets-1.50.0" => Some(include_bytes!("generated_schemas_vassets-1.50.0.json.zst")),
        "assets-1.49.2" => Some(include_bytes!("generated_schemas_vassets-1.49.2.json.zst")),
        "assets-1.49.1" => Some(include_bytes!("generated_schemas_vassets-1.49.1.json.zst")),
        "assets-1.49.0" => Some(include_bytes!("generated_schemas_vassets-1.49.0.json.zst")),
        "assets-1.48.0" => Some(include_bytes!("generated_schemas_vassets-1.48.0.json.zst")),
        "assets-1.47.0" => Some(include_bytes!("generated_schemas_vassets-1.47.0.json.zst")),
        "assets-1.46.1" => Some(include_bytes!("generated_schemas_vassets-1.46.1.json.zst")),
        "assets-1.46.0" => Some(include_bytes!("generated_schemas_vassets-1.46.0.json.zst")),
        "assets-1.45.0" => Some(include_bytes!("generated_schemas_vassets-1.45.0.json.zst")),
        "assets-1.44.0" => Some(include_bytes!("generated_schemas_vassets-1.44.0.json.zst")),
        "assets-1.43.0" => Some(include_bytes!("generated_schemas_vassets-1.43.0.json.zst")),
        "assets-1.42.0" => Some(include_bytes!("generated_schemas_vassets-1.42.0.json.zst")),
        "assets-1.41.0" => Some(include_bytes!("generated_schemas_vassets-1.41.0.json.zst")),
        "assets-1.40.0" => Some(include_bytes!("generated_schemas_vassets-1.40.0.json.zst")),
        "assets-1.39.0" => Some(include_bytes!("generated_schemas_vassets-1.39.0.json.zst")),
        "assets-1.38.0" => Some(include_bytes!("generated_schemas_vassets-1.38.0.json.zst")),
        "assets-1.37.0" => Some(include_bytes!("generated_schemas_vassets-1.37.0.json.zst")),
        "assets-1.36.1" => Some(include_bytes!("generated_schemas_vassets-1.36.1.json.zst")),
        "assets-1.36.0" => Some(include_bytes!("generated_schemas_vassets-1.36.0.json.zst")),
        "assets-1.35.1" => Some(include_bytes!("generated_schemas_vassets-1.35.1.json.zst")),
        "assets-1.35.0" => Some(include_bytes!("generated_schemas_vassets-1.35.0.json.zst")),
        "assets-1.34.0" => Some(include_bytes!("generated_schemas_vassets-1.34.0.json.zst")),
        "assets-1.33.0" => Some(include_bytes!("generated_schemas_vassets-1.33.0.json.zst")),
        "assets-1.32.2" => Some(include_bytes!("generated_schemas_vassets-1.32.2.json.zst")),
        "assets-1.32.1" => Some(include_bytes!("generated_schemas_vassets-1.32.1.json.zst")),
        "assets-1.32.0" => Some(include_bytes!("generated_schemas_vassets-1.32.0.json.zst")),
        "assets-1.31.0" => Some(include_bytes!("generated_schemas_vassets-1.31.0.json.zst")),
        "assets-1.30.0" => Some(include_bytes!("generated_schemas_vassets-1.30.0.json.zst")),
        "assets-1.29.0" => Some(include_bytes!("generated_schemas_vassets-1.29.0.json.zst")),
        "assets-1.28.0" => Some(include_bytes!("generated_schemas_vassets-1.28.0.json.zst")),
        "assets-1.27.0" => Some(include_bytes!("generated_schemas_vassets-1.27.0.json.zst")),
        "assets-1.26.0" => Some(include_bytes!("generated_schemas_vassets-1.26.0.json.zst")),
        "assets-1.25.1" => Some(include_bytes!("generated_schemas_vassets-1.25.1.json.zst")),
        "assets-1.25.0" => Some(include_bytes!("generated_schemas_vassets-1.25.0.json.zst")),
        "assets-1.24.0" => Some(include_bytes!("generated_schemas_vassets-1.24.0.json.zst")),
        "assets-1.23.0" => Some(include_bytes!("generated_schemas_vassets-1.23.0.json.zst")),
        "assets-1.22.1" => Some(include_bytes!("generated_schemas_vassets-1.22.1.json.zst")),
        "assets-1.22.0" => Some(include_bytes!("generated_schemas_vassets-1.22.0.json.zst")),
        "assets-1.21.0" => Some(include_bytes!("generated_schemas_vassets-1.21.0.json.zst")),
        "assets-1.20.0" => Some(include_bytes!("generated_schemas_vassets-1.20.0.json.zst")),
        "assets-1.19.0" => Some(include_bytes!("generated_schemas_vassets-1.19.0.json.zst")),
        "assets-1.18.0" => Some(include_bytes!("generated_schemas_vassets-1.18.0.json.zst")),
        "assets-1.17.0" => Some(include_bytes!("generated_schemas_vassets-1.17.0.json.zst")),
        "assets-1.16.0" => Some(include_bytes!("generated_schemas_vassets-1.16.0.json.zst")),
        "assets-1.15.0" => Some(include_bytes!("generated_schemas_vassets-1.15.0.json.zst")),
        "assets-1.14.0" => Some(include_bytes!("generated_schemas_vassets-1.14.0.json.zst")),
        "assets-1.13.0" => Some(include_bytes!("generated_schemas_vassets-1.13.0.json.zst")),
        "assets-1.12.0" => Some(include_bytes!("generated_schemas_vassets-1.12.0.json.zst")),
        "assets-1.11.0" => Some(include_bytes!("generated_schemas_vassets-1.11.0.json.zst")),
        "assets-1.10.0" => Some(include_bytes!("generated_schemas_vassets-1.10.0.json.zst")),
        "assets-1.9.1" => Some(include_bytes!("generated_schemas_vassets-1.9.1.json.zst")),
        "assets-1.9.0" => Some(include_bytes!("generated_schemas_vassets-1.9.0.json.zst")),
        "assets-1.8.2" => Some(include_bytes!("generated_schemas_vassets-1.8.2.json.zst")),
        "assets-1.8.1" => Some(include_bytes!("generated_schemas_vassets-1.8.1.json.zst")),
        "assets-1.8.0" => Some(include_bytes!("generated_schemas_vassets-1.8.0.json.zst")),
        "assets-1.7.0" => Some(include_bytes!("generated_schemas_vassets-1.7.0.json.zst")),
        "assets-1.6.0" => Some(include_bytes!("generated_schemas_vassets-1.6.0.json.zst")),
        "assets-1.5.1" => Some(include_bytes!("generated_schemas_vassets-1.5.1.json.zst")),
        "assets-1.5.0" => Some(include_bytes!("generated_schemas_vassets-1.5.0.json.zst")),
        "assets-1.4.2" => Some(include_bytes!("generated_schemas_vassets-1.4.2.json.zst")),
        "assets-1.4.1" => Some(include_bytes!("generated_schemas_vassets-1.4.1.json.zst")),
        "assets-1.4.0" => Some(include_bytes!("generated_schemas_vassets-1.4.0.json.zst")),
        "assets-1.3.3" => Some(include_bytes!("generated_schemas_vassets-1.3.3.json.zst")),
        "assets-1.3.2" => Some(include_bytes!("generated_schemas_vassets-1.3.2.json.zst")),
        "assets-1.3.1" => Some(include_bytes!("generated_schemas_vassets-1.3.1.json.zst")),
        "assets-1.3.0" => Some(include_bytes!("generated_schemas_vassets-1.3.0.json.zst")),
        "assets-1.2.1" => Some(include_bytes!("generated_schemas_vassets-1.2.1.json.zst")),
        "assets-1.2.0" => Some(include_bytes!("generated_schemas_vassets-1.2.0.json.zst")),
        "assets-1.1.0" => Some(include_bytes!("generated_schemas_vassets-1.1.0.json.zst")),
        "assets-1.0.1" => Some(include_bytes!("generated_schemas_vassets-1.0.1.json.zst")),
        "assets-1.0.0" => Some(include_bytes!("generated_schemas_vassets-1.0.0.json.zst")),
        "operations-management-1.10.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.10.0.json.zst"
        )),
        "operations-management-1.9.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.9.0.json.zst"
        )),
        "operations-management-1.8.1" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.8.1.json.zst"
        )),
        "operations-management-1.8.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.8.0.json.zst"
        )),
        "operations-management-1.7.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.7.0.json.zst"
        )),
        "operations-management-1.6.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.6.0.json.zst"
        )),
        "operations-management-1.5.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.5.0.json.zst"
        )),
        "operations-management-1.4.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.4.0.json.zst"
        )),
        "operations-management-1.3.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.3.0.json.zst"
        )),
        "operations-management-1.2.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.2.0.json.zst"
        )),
        "operations-management-1.1.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.1.0.json.zst"
        )),
        "operations-management-1.0.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-1.0.0.json.zst"
        )),
        "operations-management-0.2.2" => Some(include_bytes!(
            "generated_schemas_voperations-management-0.2.2.json.zst"
        )),
        "operations-management-0.2.1" => Some(include_bytes!(
            "generated_schemas_voperations-management-0.2.1.json.zst"
        )),
        "operations-management-0.2.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-0.2.0.json.zst"
        )),
        "operations-management-0.1.0" => Some(include_bytes!(
            "generated_schemas_voperations-management-0.1.0.json.zst"
        )),
        "operations-management-0.0.2" => Some(include_bytes!(
            "generated_schemas_voperations-management-0.0.2.json.zst"
        )),
        "operations-management-0.0.1" => Some(include_bytes!(
            "generated_schemas_voperations-management-0.0.1.json.zst"
        )),
        "visitors-2.0.0" => Some(include_bytes!("generated_schemas_vvisitors-2.0.0.json.zst")),
        "visitors-1.2.0" => Some(include_bytes!("generated_schemas_vvisitors-1.2.0.json.zst")),
        "visitors-1.1.0" => Some(include_bytes!("generated_schemas_vvisitors-1.1.0.json.zst")),
        "visitors-1.0.1" => Some(include_bytes!("generated_schemas_vvisitors-1.0.1.json.zst")),
        "visitors-1.0.0" => Some(include_bytes!("generated_schemas_vvisitors-1.0.0.json.zst")),
        "supporting-files-2.7.11" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.11.json.zst"
        )),
        "supporting-files-2.7.10" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.10.json.zst"
        )),
        "supporting-files-2.7.9" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.9.json.zst"
        )),
        "supporting-files-2.7.8" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.8.json.zst"
        )),
        "supporting-files-2.7.7" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.7.json.zst"
        )),
        "supporting-files-2.7.6" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.6.json.zst"
        )),
        "supporting-files-2.7.5" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.5.json.zst"
        )),
        "supporting-files-2.7.4" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.4.json.zst"
        )),
        "supporting-files-2.7.3" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.3.json.zst"
        )),
        "supporting-files-2.7.2" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.2.json.zst"
        )),
        "supporting-files-2.7.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.1.json.zst"
        )),
        "supporting-files-2.7.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.7.0.json.zst"
        )),
        "supporting-files-2.6.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.6.0.json.zst"
        )),
        "supporting-files-2.5.2" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.5.2.json.zst"
        )),
        "supporting-files-2.5.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.5.1.json.zst"
        )),
        "supporting-files-2.5.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-2.5.0.json.zst"
        )),
        "supporting-files-1.58.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.58.0.json.zst"
        )),
        "supporting-files-1.57.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.57.0.json.zst"
        )),
        "supporting-files-1.56.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.56.0.json.zst"
        )),
        "supporting-files-1.55.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.55.1.json.zst"
        )),
        "supporting-files-1.55.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.55.0.json.zst"
        )),
        "supporting-files-1.54.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.54.0.json.zst"
        )),
        "supporting-files-1.53.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.53.0.json.zst"
        )),
        "supporting-files-1.52.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.52.0.json.zst"
        )),
        "supporting-files-1.51.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.51.0.json.zst"
        )),
        "supporting-files-1.50.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.50.0.json.zst"
        )),
        "supporting-files-1.49.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.49.0.json.zst"
        )),
        "supporting-files-1.48.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.48.0.json.zst"
        )),
        "supporting-files-1.47.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.47.0.json.zst"
        )),
        "supporting-files-1.46.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.46.0.json.zst"
        )),
        "supporting-files-1.45.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.45.0.json.zst"
        )),
        "supporting-files-1.44.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.44.0.json.zst"
        )),
        "supporting-files-1.43.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.43.0.json.zst"
        )),
        "supporting-files-1.42.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.42.0.json.zst"
        )),
        "supporting-files-1.41.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.41.0.json.zst"
        )),
        "supporting-files-1.40.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.40.0.json.zst"
        )),
        "supporting-files-1.39.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.39.0.json.zst"
        )),
        "supporting-files-1.38.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.38.1.json.zst"
        )),
        "supporting-files-1.38.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.38.0.json.zst"
        )),
        "supporting-files-1.37.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.37.0.json.zst"
        )),
        "supporting-files-1.36.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.36.1.json.zst"
        )),
        "supporting-files-1.36.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.36.0.json.zst"
        )),
        "supporting-files-1.35.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.35.1.json.zst"
        )),
        "supporting-files-1.35.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.35.0.json.zst"
        )),
        "supporting-files-1.34.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.34.0.json.zst"
        )),
        "supporting-files-1.33.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.33.1.json.zst"
        )),
        "supporting-files-1.33.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.33.0.json.zst"
        )),
        "supporting-files-1.32.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.32.0.json.zst"
        )),
        "supporting-files-1.31.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.31.0.json.zst"
        )),
        "supporting-files-1.30.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.30.1.json.zst"
        )),
        "supporting-files-1.30.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.30.0.json.zst"
        )),
        "supporting-files-1.29.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.29.0.json.zst"
        )),
        "supporting-files-1.28.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.28.0.json.zst"
        )),
        "supporting-files-1.27.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.27.0.json.zst"
        )),
        "supporting-files-1.26.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.26.0.json.zst"
        )),
        "supporting-files-1.25.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.25.0.json.zst"
        )),
        "supporting-files-1.24.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.24.0.json.zst"
        )),
        "supporting-files-1.23.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.23.0.json.zst"
        )),
        "supporting-files-1.22.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.22.0.json.zst"
        )),
        "supporting-files-1.21.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.21.0.json.zst"
        )),
        "supporting-files-1.20.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.20.0.json.zst"
        )),
        "supporting-files-1.19.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.19.0.json.zst"
        )),
        "supporting-files-1.18.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.18.0.json.zst"
        )),
        "supporting-files-1.17.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.17.1.json.zst"
        )),
        "supporting-files-1.17.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.17.0.json.zst"
        )),
        "supporting-files-1.16.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.16.0.json.zst"
        )),
        "supporting-files-1.15.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.15.1.json.zst"
        )),
        "supporting-files-1.15.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.15.0.json.zst"
        )),
        "supporting-files-1.14.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.14.0.json.zst"
        )),
        "supporting-files-1.13.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.13.0.json.zst"
        )),
        "supporting-files-1.12.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.12.0.json.zst"
        )),
        "supporting-files-1.11.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.11.0.json.zst"
        )),
        "supporting-files-1.10.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.10.0.json.zst"
        )),
        "supporting-files-1.9.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.9.0.json.zst"
        )),
        "supporting-files-1.8.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.8.0.json.zst"
        )),
        "supporting-files-1.7.3" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.7.3.json.zst"
        )),
        "supporting-files-1.7.2" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.7.2.json.zst"
        )),
        "supporting-files-1.7.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.7.1.json.zst"
        )),
        "supporting-files-1.7.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.7.0.json.zst"
        )),
        "supporting-files-1.6.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.6.0.json.zst"
        )),
        "supporting-files-1.5.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.5.0.json.zst"
        )),
        "supporting-files-1.4.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.4.0.json.zst"
        )),
        "supporting-files-1.3.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.3.0.json.zst"
        )),
        "supporting-files-1.2.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.2.0.json.zst"
        )),
        "supporting-files-1.1.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.1.0.json.zst"
        )),
        "supporting-files-1.0.0" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-1.0.0.json.zst"
        )),
        "supporting-files-0.0.2" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-0.0.2.json.zst"
        )),
        "supporting-files-0.0.1" => Some(include_bytes!(
            "generated_schemas_vsupporting-files-0.0.1.json.zst"
        )),
        "access-roles-saas" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-saas.json.zst"
        )),
        "access-roles-va-release-1-2022" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-1-2022.json.zst"
        )),
        "access-roles-va-release-2-2022" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-2-2022.json.zst"
        )),
        "access-roles-va-release-3-2022" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-3-2022.json.zst"
        )),
        "access-roles-va-release-1-2023" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-1-2023.json.zst"
        )),
        "access-roles-va-release-2-2023" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-2-2023.json.zst"
        )),
        "access-roles-va-release-3-2023" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-3-2023.json.zst"
        )),
        "access-roles-va-release-1-2024" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-1-2024.json.zst"
        )),
        "access-roles-va-release-2-2024" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-2-2024.json.zst"
        )),
        "access-roles-va-release-3-2024" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-3-2024.json.zst"
        )),
        "access-roles-va-release-4-2024" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-4-2024.json.zst"
        )),
        "access-roles-va-release-1-2025" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-1-2025.json.zst"
        )),
        "access-roles-va-release-2-2025" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-2-2025.json.zst"
        )),
        "access-roles-va-release-3-2025" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-3-2025.json.zst"
        )),
        "access-roles-va-release-4-2025" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-4-2025.json.zst"
        )),
        "access-roles-va-release-1-2026" => Some(include_bytes!(
            "generated_schemas_vaccess-roles-va-release-1-2026.json.zst"
        )),
        "lookandfeel-1.0.0" => Some(include_bytes!(
            "generated_schemas_vlookandfeel-1.0.0.json.zst"
        )),
        "task-notifications-1.0.0" => Some(include_bytes!(
            "generated_schemas_vtask-notifications-1.0.0.json.zst"
        )),
        "settings-1.1.0" => Some(include_bytes!("generated_schemas_vsettings-1.1.0.json.zst")),
        "settings-1.0.0" => Some(include_bytes!("generated_schemas_vsettings-1.0.0.json.zst")),
        "custom-action-support-saas" => Some(include_bytes!(
            "generated_schemas_vcustom-action-support-saas.json.zst"
        )),
        "custom-action-support-va-release-1-2021" => Some(include_bytes!(
            "generated_schemas_vcustom-action-support-va-release-1-2021.json.zst"
        )),
        "custom-action-support-va-release-2-2021" => Some(include_bytes!(
            "generated_schemas_vcustom-action-support-va-release-2-2021.json.zst"
        )),
        "custom-action-support-va-release-3-2021" => Some(include_bytes!(
            "generated_schemas_vcustom-action-support-va-release-3-2021.json.zst"
        )),
        "custom-action-support-va-release-4-2021" => Some(include_bytes!(
            "generated_schemas_vcustom-action-support-va-release-4-2021.json.zst"
        )),
        "custom-action-support-va-release-1-2022" => Some(include_bytes!(
            "generated_schemas_vcustom-action-support-va-release-1-2022.json.zst"
        )),
        "custom-action-support-va-release-2-2022" => Some(include_bytes!(
            "generated_schemas_vcustom-action-support-va-release-2-2022.json.zst"
        )),
        "custom-action-support-va-release-3-2022" => Some(include_bytes!(
            "generated_schemas_vcustom-action-support-va-release-3-2022.json.zst"
        )),
        "custom-action-support-va-release-1-2023-or-newer" => Some(include_bytes!(
            "generated_schemas_vcustom-action-support-va-release-1-2023-or-newer.json.zst"
        )),
        _ => None,
    }
}
// mcpify:versions:end

fn schemas_by_operation(api_version: &str) -> &'static HashMap<String, OperationSchemas> {
    static SCHEMAS: OnceLock<Mutex<HashMap<String, &'static HashMap<String, OperationSchemas>>>> =
        OnceLock::new();
    static EMPTY: OnceLock<HashMap<String, OperationSchemas>> = OnceLock::new();
    let empty = EMPTY.get_or_init(HashMap::new);

    let cache = SCHEMAS.get_or_init(|| Mutex::new(HashMap::new()));
    let mut cache = cache.lock().unwrap();
    if let Some(schemas) = cache.get(api_version) {
        return schemas;
    }

    let Some(compressed) = schemas_zst_for(api_version) else {
        return empty;
    };
    let parsed: HashMap<String, OperationSchemas> = zstd::decode_all(compressed)
        .ok()
        .and_then(|json| serde_json::from_slice(&json).ok())
        .unwrap_or_default();
    let leaked: &'static HashMap<String, OperationSchemas> = Box::leak(Box::new(parsed));
    cache.insert(api_version.to_string(), leaked);
    leaked
}

fn validate_against(
    cache: &Mutex<HashMap<String, jsonschema::Validator>>,
    operation_id: &str,
    schema: &Value,
    data: &Value,
) -> Result<(), Vec<String>> {
    let mut cache = cache.lock().unwrap();
    let validator = cache.entry(operation_id.to_string()).or_insert_with(|| {
        jsonschema::validator_for(schema).unwrap_or_else(|_| {
            jsonschema::validator_for(&Value::Object(Default::default())).unwrap()
        })
    });

    if validator.is_valid(data) {
        return Ok(());
    }
    let errors = validator
        .iter_errors(data)
        .map(|error| error.to_string())
        .collect::<Vec<_>>();
    Err(errors)
}

/// Returns `Err` if `data` doesn't satisfy `operation_id`'s input schema,
/// for the given `api_version`.
pub fn validate_input(
    api_version: &str,
    operation_id: &str,
    data: &Value,
) -> Result<(), McpifyError> {
    static CACHE: OnceLock<Mutex<HashMap<String, jsonschema::Validator>>> = OnceLock::new();
    let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));

    let empty = Value::Object(Default::default());
    let schema = schemas_by_operation(api_version)
        .get(operation_id)
        .map(|schemas| &schemas.input_schema)
        .unwrap_or(&empty);

    let cache_key = format!("{api_version} {operation_id}");
    validate_against(cache, &cache_key, schema, data).map_err(|errors| McpifyError::Validation {
        message: format!("invalid input for '{operation_id}'"),
        details: Some(serde_json::json!(errors)),
    })
}

/// Returns `Err` if `data` doesn't satisfy `operation_id`'s output schema
/// — surfaces upstream API drift as a structured error rather than
/// silently returning a mismatched response (architecture.md's `call`
/// pipeline). Validates against the given `api_version`'s schema.
pub fn validate_output(
    api_version: &str,
    operation_id: &str,
    data: &Value,
) -> Result<(), McpifyError> {
    static CACHE: OnceLock<Mutex<HashMap<String, jsonschema::Validator>>> = OnceLock::new();
    let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));

    let empty = Value::Object(Default::default());
    let schema = schemas_by_operation(api_version)
        .get(operation_id)
        .map(|schemas| &schemas.output_schema)
        .unwrap_or(&empty);

    let cache_key = format!("{api_version} {operation_id}");
    validate_against(cache, &cache_key, schema, data).map_err(|errors| McpifyError::Validation {
        message: format!("unexpected response shape for '{operation_id}'"),
        details: Some(serde_json::json!(errors)),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    // These tests deliberately use an operationId that generated_schemas.json
    // never declares — they exercise the "no schema found" fallback (an
    // always-valid `{}` schema), rather than any spec-dependent content
    // this project's own generation happened to produce.

    #[test]
    fn an_unknown_operation_id_falls_back_to_an_always_valid_schema() {
        assert!(
            validate_input(
                "general-1.2.0",
                "__unknown_operation__",
                &serde_json::json!({"anything": true})
            )
            .is_ok()
        );
        assert!(
            validate_output(
                "general-1.2.0",
                "__unknown_operation__",
                &serde_json::json!(42)
            )
            .is_ok()
        );
    }

    #[test]
    fn an_unknown_api_version_also_falls_back_to_an_always_valid_schema() {
        assert!(
            validate_input(
                "__unknown_version__",
                "__unknown_operation__",
                &serde_json::json!({"anything": true})
            )
            .is_ok()
        );
    }

    #[test]
    fn validate_against_reports_every_schema_violation() {
        static CACHE: OnceLock<Mutex<HashMap<String, jsonschema::Validator>>> = OnceLock::new();
        let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
        let schema = serde_json::json!({
            "type": "object",
            "required": ["name"],
            "properties": { "name": { "type": "string" } },
        });

        let ok = validate_against(
            cache,
            "test_op_ok",
            &schema,
            &serde_json::json!({"name": "widget"}),
        );
        assert!(ok.is_ok());

        let err = validate_against(cache, "test_op_missing", &schema, &serde_json::json!({}));
        assert!(err.is_err());
    }
}
