// General API MCP server — generated by mcpify. Do not hand-edit.
//
// Interactive setup wizard (REQ-1.6): collects the API URL and the
// credentials the discovered auth scheme(s) need, then persists them per
// the operator's choice: a .env file, a config.json file, or a
// ready-to-run CLI invocation printed to stdout (nothing written to disk).
// `inquire`'s prompts are blocking — run through `spawn_blocking`, the
// same pattern mcpify's own `auth_profile::prompt` documents for calling
// it from an async runtime.

use std::collections::HashMap;
use std::time::Duration;

use topdesk_mcp::core::config_schema::{AuthMethod, Transport};
use topdesk_mcp::core::credential_storage::save_credential;

fn to_env_key(key: &str) -> String {
    key.to_uppercase()
}

async fn prompt_base_url() -> anyhow::Result<String> {
    let url = tokio::task::spawn_blocking(|| inquire::Text::new("General API base URL:").prompt())
        .await??;

    let client = reqwest::Client::new();
    match client
        .head(&url)
        .timeout(Duration::from_secs(5))
        .send()
        .await
    {
        Ok(_) => println!("reachable"),
        Err(_) => println!(
            "could not reach that URL yet — continuing anyway (fix it later with `test-connection`)"
        ),
    }

    Ok(url)
}

async fn prompt_auth_method() -> anyhow::Result<AuthMethod> {
    // Exactly one scheme was discovered — nothing to choose between.
    Ok(AuthMethod::Basic)
}

// mcpify:versions:begin
async fn prompt_api_version() -> anyhow::Result<String> {
    let choices = vec![
        "general-1.2.0 (default/latest)",
        "general-1.1.1",
        "general-1.1.0",
        "general-1.0.0",
        "incident-4.2.6",
        "incident-4.2.5",
        "incident-4.2.4",
        "incident-4.2.3",
        "incident-4.2.2",
        "incident-4.2.1",
        "incident-4.2.0",
        "incident-4.1.0",
        "incident-4.0.0",
        "incident-3.9.1",
        "incident-3.9.0",
        "incident-3.8.5",
        "incident-3.8.4",
        "incident-3.8.3",
        "incident-3.8.2",
        "incident-3.8.1",
        "incident-3.8.0",
        "incident-3.7.1",
        "knowledge-base-before-explorer-migration",
        "knowledge-base-after-explorer-migration",
        "knowledgebase-graphql-1.0.0",
        "reservations-2.0.0",
        "reservations-1.23.0",
        "reservations-1.22.0",
        "reservations-1.21.1",
        "reservations-1.21.0",
        "reservations-1.20.0",
        "reservations-1.19.0",
        "reservations-1.18.0",
        "reservations-1.17.0",
        "reservations-1.16.0",
        "reservations-1.15.0",
        "reservations-1.14.0",
        "reservations-1.13.0",
        "reservations-1.12.0",
        "reservations-1.11.0",
        "reservations-1.10.0",
        "reservations-1.9.0",
        "reservations-1.8.0",
        "reservations-1.7.0",
        "reservations-1.6.0",
        "reservations-1.5.0",
        "reservations-1.4.0",
        "reservations-1.3.0",
        "reservations-1.2.0",
        "reservations-1.1.0",
        "reservations-1.0.0",
        "services-1.3.7",
        "services-1.3.6",
        "services-1.3.5",
        "services-1.3.4",
        "services-1.3.3",
        "services-1.3.2",
        "services-1.3.1",
        "services-1.3.0",
        "services-1.2.0",
        "services-1.1.0",
        "services-1.0.0",
        "change-1.4.0",
        "change-1.3.7",
        "change-1.3.6",
        "change-1.3.5",
        "change-1.3.4",
        "change-1.3.3",
        "change-1.3.2",
        "change-1.3.1",
        "change-1.3.0",
        "change-1.2.5",
        "change-1.2.4",
        "change-1.2.3",
        "change-1.2.2",
        "change-1.2.1",
        "change-1.2.0",
        "change-1.1.4",
        "change-1.1.3",
        "change-1.1.2",
        "change-1.1.1",
        "change-1.1.0",
        "change-1.0.2",
        "change-1.0.1",
        "change-1.0.0",
        "assets-1.91.1",
        "assets-1.91.0",
        "assets-1.90.0",
        "assets-1.89.0",
        "assets-1.88.0",
        "assets-1.87.0",
        "assets-1.86.0",
        "assets-1.85.0",
        "assets-1.84.0",
        "assets-1.83.0",
        "assets-1.82.0",
        "assets-1.81.5",
        "assets-1.81.4",
        "assets-1.81.3",
        "assets-1.81.2",
        "assets-1.81.1",
        "assets-1.81.0",
        "assets-1.80.0",
        "assets-1.79.1",
        "assets-1.79.0",
        "assets-1.78.0",
        "assets-1.77.0",
        "assets-1.76.0",
        "assets-1.75.0",
        "assets-1.74.0",
        "assets-1.73.0",
        "assets-1.72.0",
        "assets-1.71.0",
        "assets-1.70.0",
        "assets-1.69.0",
        "assets-1.68.0",
        "assets-1.67.1",
        "assets-1.67.0",
        "assets-1.66.0",
        "assets-1.65.0",
        "assets-1.64.0",
        "assets-1.63.2",
        "assets-1.63.1",
        "assets-1.63.0",
        "assets-1.62.0",
        "assets-1.61.0",
        "assets-1.60.0",
        "assets-1.59.1",
        "assets-1.59.0",
        "assets-1.58.0",
        "assets-1.57.0",
        "assets-1.56.0",
        "assets-1.55.0",
        "assets-1.54.0",
        "assets-1.53.0",
        "assets-1.52.1",
        "assets-1.52.0",
        "assets-1.51.3",
        "assets-1.51.2",
        "assets-1.51.1",
        "assets-1.51.0",
        "assets-1.50.1",
        "assets-1.50.0",
        "assets-1.49.2",
        "assets-1.49.1",
        "assets-1.49.0",
        "assets-1.48.0",
        "assets-1.47.0",
        "assets-1.46.1",
        "assets-1.46.0",
        "assets-1.45.0",
        "assets-1.44.0",
        "assets-1.43.0",
        "assets-1.42.0",
        "assets-1.41.0",
        "assets-1.40.0",
        "assets-1.39.0",
        "assets-1.38.0",
        "assets-1.37.0",
        "assets-1.36.1",
        "assets-1.36.0",
        "assets-1.35.1",
        "assets-1.35.0",
        "assets-1.34.0",
        "assets-1.33.0",
        "assets-1.32.2",
        "assets-1.32.1",
        "assets-1.32.0",
        "assets-1.31.0",
        "assets-1.30.0",
        "assets-1.29.0",
        "assets-1.28.0",
        "assets-1.27.0",
        "assets-1.26.0",
        "assets-1.25.1",
        "assets-1.25.0",
        "assets-1.24.0",
        "assets-1.23.0",
        "assets-1.22.1",
        "assets-1.22.0",
        "assets-1.21.0",
        "assets-1.20.0",
        "assets-1.19.0",
        "assets-1.18.0",
        "assets-1.17.0",
        "assets-1.16.0",
        "assets-1.15.0",
        "assets-1.14.0",
        "assets-1.13.0",
        "assets-1.12.0",
        "assets-1.11.0",
        "assets-1.10.0",
        "assets-1.9.1",
        "assets-1.9.0",
        "assets-1.8.2",
        "assets-1.8.1",
        "assets-1.8.0",
        "assets-1.7.0",
        "assets-1.6.0",
        "assets-1.5.1",
        "assets-1.5.0",
        "assets-1.4.2",
        "assets-1.4.1",
        "assets-1.4.0",
        "assets-1.3.3",
        "assets-1.3.2",
        "assets-1.3.1",
        "assets-1.3.0",
        "assets-1.2.1",
        "assets-1.2.0",
        "assets-1.1.0",
        "assets-1.0.1",
        "assets-1.0.0",
        "operations-management-1.10.0",
        "operations-management-1.9.0",
        "operations-management-1.8.1",
        "operations-management-1.8.0",
        "operations-management-1.7.0",
        "operations-management-1.6.0",
        "operations-management-1.5.0",
        "operations-management-1.4.0",
        "operations-management-1.3.0",
        "operations-management-1.2.0",
        "operations-management-1.1.0",
        "operations-management-1.0.0",
        "operations-management-0.2.2",
        "operations-management-0.2.1",
        "operations-management-0.2.0",
        "operations-management-0.1.0",
        "operations-management-0.0.2",
        "operations-management-0.0.1",
        "visitors-2.0.0",
        "visitors-1.2.0",
        "visitors-1.1.0",
        "visitors-1.0.1",
        "visitors-1.0.0",
        "supporting-files-2.7.11",
        "supporting-files-2.7.10",
        "supporting-files-2.7.9",
        "supporting-files-2.7.8",
        "supporting-files-2.7.7",
        "supporting-files-2.7.6",
        "supporting-files-2.7.5",
        "supporting-files-2.7.4",
        "supporting-files-2.7.3",
        "supporting-files-2.7.2",
        "supporting-files-2.7.1",
        "supporting-files-2.7.0",
        "supporting-files-2.6.0",
        "supporting-files-2.5.2",
        "supporting-files-2.5.1",
        "supporting-files-2.5.0",
        "supporting-files-1.58.0",
        "supporting-files-1.57.0",
        "supporting-files-1.56.0",
        "supporting-files-1.55.1",
        "supporting-files-1.55.0",
        "supporting-files-1.54.0",
        "supporting-files-1.53.0",
        "supporting-files-1.52.0",
        "supporting-files-1.51.0",
        "supporting-files-1.50.0",
        "supporting-files-1.49.0",
        "supporting-files-1.48.0",
        "supporting-files-1.47.0",
        "supporting-files-1.46.0",
        "supporting-files-1.45.0",
        "supporting-files-1.44.0",
        "supporting-files-1.43.0",
        "supporting-files-1.42.0",
        "supporting-files-1.41.0",
        "supporting-files-1.40.0",
        "supporting-files-1.39.0",
        "supporting-files-1.38.1",
        "supporting-files-1.38.0",
        "supporting-files-1.37.0",
        "supporting-files-1.36.1",
        "supporting-files-1.36.0",
        "supporting-files-1.35.1",
        "supporting-files-1.35.0",
        "supporting-files-1.34.0",
        "supporting-files-1.33.1",
        "supporting-files-1.33.0",
        "supporting-files-1.32.0",
        "supporting-files-1.31.0",
        "supporting-files-1.30.1",
        "supporting-files-1.30.0",
        "supporting-files-1.29.0",
        "supporting-files-1.28.0",
        "supporting-files-1.27.0",
        "supporting-files-1.26.0",
        "supporting-files-1.25.0",
        "supporting-files-1.24.0",
        "supporting-files-1.23.0",
        "supporting-files-1.22.0",
        "supporting-files-1.21.0",
        "supporting-files-1.20.0",
        "supporting-files-1.19.0",
        "supporting-files-1.18.0",
        "supporting-files-1.17.1",
        "supporting-files-1.17.0",
        "supporting-files-1.16.0",
        "supporting-files-1.15.1",
        "supporting-files-1.15.0",
        "supporting-files-1.14.0",
        "supporting-files-1.13.0",
        "supporting-files-1.12.0",
        "supporting-files-1.11.0",
        "supporting-files-1.10.0",
        "supporting-files-1.9.0",
        "supporting-files-1.8.0",
        "supporting-files-1.7.3",
        "supporting-files-1.7.2",
        "supporting-files-1.7.1",
        "supporting-files-1.7.0",
        "supporting-files-1.6.0",
        "supporting-files-1.5.0",
        "supporting-files-1.4.0",
        "supporting-files-1.3.0",
        "supporting-files-1.2.0",
        "supporting-files-1.1.0",
        "supporting-files-1.0.0",
        "supporting-files-0.0.2",
        "supporting-files-0.0.1",
        "access-roles-saas",
        "access-roles-va-release-1-2022",
        "access-roles-va-release-2-2022",
        "access-roles-va-release-3-2022",
        "access-roles-va-release-1-2023",
        "access-roles-va-release-2-2023",
        "access-roles-va-release-3-2023",
        "access-roles-va-release-1-2024",
        "access-roles-va-release-2-2024",
        "access-roles-va-release-3-2024",
        "access-roles-va-release-4-2024",
        "access-roles-va-release-1-2025",
        "access-roles-va-release-2-2025",
        "access-roles-va-release-3-2025",
        "access-roles-va-release-4-2025",
        "access-roles-va-release-1-2026",
        "lookandfeel-1.0.0",
        "task-notifications-1.0.0",
        "settings-1.1.0",
        "settings-1.0.0",
        "custom-action-support-saas",
        "custom-action-support-va-release-1-2021",
        "custom-action-support-va-release-2-2021",
        "custom-action-support-va-release-3-2021",
        "custom-action-support-va-release-4-2021",
        "custom-action-support-va-release-1-2022",
        "custom-action-support-va-release-2-2022",
        "custom-action-support-va-release-3-2022",
        "custom-action-support-va-release-1-2023-or-newer",
    ];
    let selection = tokio::task::spawn_blocking(move || {
        inquire::Select::new("API version to use:", choices).prompt()
    })
    .await??;

    Ok(match selection {
        "general-1.2.0 (default/latest)" => "general-1.2.0".to_string(),
        "general-1.1.1" => "general-1.1.1".to_string(),
        "general-1.1.0" => "general-1.1.0".to_string(),
        "general-1.0.0" => "general-1.0.0".to_string(),
        "incident-4.2.6" => "incident-4.2.6".to_string(),
        "incident-4.2.5" => "incident-4.2.5".to_string(),
        "incident-4.2.4" => "incident-4.2.4".to_string(),
        "incident-4.2.3" => "incident-4.2.3".to_string(),
        "incident-4.2.2" => "incident-4.2.2".to_string(),
        "incident-4.2.1" => "incident-4.2.1".to_string(),
        "incident-4.2.0" => "incident-4.2.0".to_string(),
        "incident-4.1.0" => "incident-4.1.0".to_string(),
        "incident-4.0.0" => "incident-4.0.0".to_string(),
        "incident-3.9.1" => "incident-3.9.1".to_string(),
        "incident-3.9.0" => "incident-3.9.0".to_string(),
        "incident-3.8.5" => "incident-3.8.5".to_string(),
        "incident-3.8.4" => "incident-3.8.4".to_string(),
        "incident-3.8.3" => "incident-3.8.3".to_string(),
        "incident-3.8.2" => "incident-3.8.2".to_string(),
        "incident-3.8.1" => "incident-3.8.1".to_string(),
        "incident-3.8.0" => "incident-3.8.0".to_string(),
        "incident-3.7.1" => "incident-3.7.1".to_string(),
        "knowledge-base-before-explorer-migration" => "knowledge-base-before-explorer-migration".to_string(),
        "knowledge-base-after-explorer-migration" => "knowledge-base-after-explorer-migration".to_string(),
        "knowledgebase-graphql-1.0.0" => "knowledgebase-graphql-1.0.0".to_string(),
        "reservations-2.0.0" => "reservations-2.0.0".to_string(),
        "reservations-1.23.0" => "reservations-1.23.0".to_string(),
        "reservations-1.22.0" => "reservations-1.22.0".to_string(),
        "reservations-1.21.1" => "reservations-1.21.1".to_string(),
        "reservations-1.21.0" => "reservations-1.21.0".to_string(),
        "reservations-1.20.0" => "reservations-1.20.0".to_string(),
        "reservations-1.19.0" => "reservations-1.19.0".to_string(),
        "reservations-1.18.0" => "reservations-1.18.0".to_string(),
        "reservations-1.17.0" => "reservations-1.17.0".to_string(),
        "reservations-1.16.0" => "reservations-1.16.0".to_string(),
        "reservations-1.15.0" => "reservations-1.15.0".to_string(),
        "reservations-1.14.0" => "reservations-1.14.0".to_string(),
        "reservations-1.13.0" => "reservations-1.13.0".to_string(),
        "reservations-1.12.0" => "reservations-1.12.0".to_string(),
        "reservations-1.11.0" => "reservations-1.11.0".to_string(),
        "reservations-1.10.0" => "reservations-1.10.0".to_string(),
        "reservations-1.9.0" => "reservations-1.9.0".to_string(),
        "reservations-1.8.0" => "reservations-1.8.0".to_string(),
        "reservations-1.7.0" => "reservations-1.7.0".to_string(),
        "reservations-1.6.0" => "reservations-1.6.0".to_string(),
        "reservations-1.5.0" => "reservations-1.5.0".to_string(),
        "reservations-1.4.0" => "reservations-1.4.0".to_string(),
        "reservations-1.3.0" => "reservations-1.3.0".to_string(),
        "reservations-1.2.0" => "reservations-1.2.0".to_string(),
        "reservations-1.1.0" => "reservations-1.1.0".to_string(),
        "reservations-1.0.0" => "reservations-1.0.0".to_string(),
        "services-1.3.7" => "services-1.3.7".to_string(),
        "services-1.3.6" => "services-1.3.6".to_string(),
        "services-1.3.5" => "services-1.3.5".to_string(),
        "services-1.3.4" => "services-1.3.4".to_string(),
        "services-1.3.3" => "services-1.3.3".to_string(),
        "services-1.3.2" => "services-1.3.2".to_string(),
        "services-1.3.1" => "services-1.3.1".to_string(),
        "services-1.3.0" => "services-1.3.0".to_string(),
        "services-1.2.0" => "services-1.2.0".to_string(),
        "services-1.1.0" => "services-1.1.0".to_string(),
        "services-1.0.0" => "services-1.0.0".to_string(),
        "change-1.4.0" => "change-1.4.0".to_string(),
        "change-1.3.7" => "change-1.3.7".to_string(),
        "change-1.3.6" => "change-1.3.6".to_string(),
        "change-1.3.5" => "change-1.3.5".to_string(),
        "change-1.3.4" => "change-1.3.4".to_string(),
        "change-1.3.3" => "change-1.3.3".to_string(),
        "change-1.3.2" => "change-1.3.2".to_string(),
        "change-1.3.1" => "change-1.3.1".to_string(),
        "change-1.3.0" => "change-1.3.0".to_string(),
        "change-1.2.5" => "change-1.2.5".to_string(),
        "change-1.2.4" => "change-1.2.4".to_string(),
        "change-1.2.3" => "change-1.2.3".to_string(),
        "change-1.2.2" => "change-1.2.2".to_string(),
        "change-1.2.1" => "change-1.2.1".to_string(),
        "change-1.2.0" => "change-1.2.0".to_string(),
        "change-1.1.4" => "change-1.1.4".to_string(),
        "change-1.1.3" => "change-1.1.3".to_string(),
        "change-1.1.2" => "change-1.1.2".to_string(),
        "change-1.1.1" => "change-1.1.1".to_string(),
        "change-1.1.0" => "change-1.1.0".to_string(),
        "change-1.0.2" => "change-1.0.2".to_string(),
        "change-1.0.1" => "change-1.0.1".to_string(),
        "change-1.0.0" => "change-1.0.0".to_string(),
        "assets-1.91.1" => "assets-1.91.1".to_string(),
        "assets-1.91.0" => "assets-1.91.0".to_string(),
        "assets-1.90.0" => "assets-1.90.0".to_string(),
        "assets-1.89.0" => "assets-1.89.0".to_string(),
        "assets-1.88.0" => "assets-1.88.0".to_string(),
        "assets-1.87.0" => "assets-1.87.0".to_string(),
        "assets-1.86.0" => "assets-1.86.0".to_string(),
        "assets-1.85.0" => "assets-1.85.0".to_string(),
        "assets-1.84.0" => "assets-1.84.0".to_string(),
        "assets-1.83.0" => "assets-1.83.0".to_string(),
        "assets-1.82.0" => "assets-1.82.0".to_string(),
        "assets-1.81.5" => "assets-1.81.5".to_string(),
        "assets-1.81.4" => "assets-1.81.4".to_string(),
        "assets-1.81.3" => "assets-1.81.3".to_string(),
        "assets-1.81.2" => "assets-1.81.2".to_string(),
        "assets-1.81.1" => "assets-1.81.1".to_string(),
        "assets-1.81.0" => "assets-1.81.0".to_string(),
        "assets-1.80.0" => "assets-1.80.0".to_string(),
        "assets-1.79.1" => "assets-1.79.1".to_string(),
        "assets-1.79.0" => "assets-1.79.0".to_string(),
        "assets-1.78.0" => "assets-1.78.0".to_string(),
        "assets-1.77.0" => "assets-1.77.0".to_string(),
        "assets-1.76.0" => "assets-1.76.0".to_string(),
        "assets-1.75.0" => "assets-1.75.0".to_string(),
        "assets-1.74.0" => "assets-1.74.0".to_string(),
        "assets-1.73.0" => "assets-1.73.0".to_string(),
        "assets-1.72.0" => "assets-1.72.0".to_string(),
        "assets-1.71.0" => "assets-1.71.0".to_string(),
        "assets-1.70.0" => "assets-1.70.0".to_string(),
        "assets-1.69.0" => "assets-1.69.0".to_string(),
        "assets-1.68.0" => "assets-1.68.0".to_string(),
        "assets-1.67.1" => "assets-1.67.1".to_string(),
        "assets-1.67.0" => "assets-1.67.0".to_string(),
        "assets-1.66.0" => "assets-1.66.0".to_string(),
        "assets-1.65.0" => "assets-1.65.0".to_string(),
        "assets-1.64.0" => "assets-1.64.0".to_string(),
        "assets-1.63.2" => "assets-1.63.2".to_string(),
        "assets-1.63.1" => "assets-1.63.1".to_string(),
        "assets-1.63.0" => "assets-1.63.0".to_string(),
        "assets-1.62.0" => "assets-1.62.0".to_string(),
        "assets-1.61.0" => "assets-1.61.0".to_string(),
        "assets-1.60.0" => "assets-1.60.0".to_string(),
        "assets-1.59.1" => "assets-1.59.1".to_string(),
        "assets-1.59.0" => "assets-1.59.0".to_string(),
        "assets-1.58.0" => "assets-1.58.0".to_string(),
        "assets-1.57.0" => "assets-1.57.0".to_string(),
        "assets-1.56.0" => "assets-1.56.0".to_string(),
        "assets-1.55.0" => "assets-1.55.0".to_string(),
        "assets-1.54.0" => "assets-1.54.0".to_string(),
        "assets-1.53.0" => "assets-1.53.0".to_string(),
        "assets-1.52.1" => "assets-1.52.1".to_string(),
        "assets-1.52.0" => "assets-1.52.0".to_string(),
        "assets-1.51.3" => "assets-1.51.3".to_string(),
        "assets-1.51.2" => "assets-1.51.2".to_string(),
        "assets-1.51.1" => "assets-1.51.1".to_string(),
        "assets-1.51.0" => "assets-1.51.0".to_string(),
        "assets-1.50.1" => "assets-1.50.1".to_string(),
        "assets-1.50.0" => "assets-1.50.0".to_string(),
        "assets-1.49.2" => "assets-1.49.2".to_string(),
        "assets-1.49.1" => "assets-1.49.1".to_string(),
        "assets-1.49.0" => "assets-1.49.0".to_string(),
        "assets-1.48.0" => "assets-1.48.0".to_string(),
        "assets-1.47.0" => "assets-1.47.0".to_string(),
        "assets-1.46.1" => "assets-1.46.1".to_string(),
        "assets-1.46.0" => "assets-1.46.0".to_string(),
        "assets-1.45.0" => "assets-1.45.0".to_string(),
        "assets-1.44.0" => "assets-1.44.0".to_string(),
        "assets-1.43.0" => "assets-1.43.0".to_string(),
        "assets-1.42.0" => "assets-1.42.0".to_string(),
        "assets-1.41.0" => "assets-1.41.0".to_string(),
        "assets-1.40.0" => "assets-1.40.0".to_string(),
        "assets-1.39.0" => "assets-1.39.0".to_string(),
        "assets-1.38.0" => "assets-1.38.0".to_string(),
        "assets-1.37.0" => "assets-1.37.0".to_string(),
        "assets-1.36.1" => "assets-1.36.1".to_string(),
        "assets-1.36.0" => "assets-1.36.0".to_string(),
        "assets-1.35.1" => "assets-1.35.1".to_string(),
        "assets-1.35.0" => "assets-1.35.0".to_string(),
        "assets-1.34.0" => "assets-1.34.0".to_string(),
        "assets-1.33.0" => "assets-1.33.0".to_string(),
        "assets-1.32.2" => "assets-1.32.2".to_string(),
        "assets-1.32.1" => "assets-1.32.1".to_string(),
        "assets-1.32.0" => "assets-1.32.0".to_string(),
        "assets-1.31.0" => "assets-1.31.0".to_string(),
        "assets-1.30.0" => "assets-1.30.0".to_string(),
        "assets-1.29.0" => "assets-1.29.0".to_string(),
        "assets-1.28.0" => "assets-1.28.0".to_string(),
        "assets-1.27.0" => "assets-1.27.0".to_string(),
        "assets-1.26.0" => "assets-1.26.0".to_string(),
        "assets-1.25.1" => "assets-1.25.1".to_string(),
        "assets-1.25.0" => "assets-1.25.0".to_string(),
        "assets-1.24.0" => "assets-1.24.0".to_string(),
        "assets-1.23.0" => "assets-1.23.0".to_string(),
        "assets-1.22.1" => "assets-1.22.1".to_string(),
        "assets-1.22.0" => "assets-1.22.0".to_string(),
        "assets-1.21.0" => "assets-1.21.0".to_string(),
        "assets-1.20.0" => "assets-1.20.0".to_string(),
        "assets-1.19.0" => "assets-1.19.0".to_string(),
        "assets-1.18.0" => "assets-1.18.0".to_string(),
        "assets-1.17.0" => "assets-1.17.0".to_string(),
        "assets-1.16.0" => "assets-1.16.0".to_string(),
        "assets-1.15.0" => "assets-1.15.0".to_string(),
        "assets-1.14.0" => "assets-1.14.0".to_string(),
        "assets-1.13.0" => "assets-1.13.0".to_string(),
        "assets-1.12.0" => "assets-1.12.0".to_string(),
        "assets-1.11.0" => "assets-1.11.0".to_string(),
        "assets-1.10.0" => "assets-1.10.0".to_string(),
        "assets-1.9.1" => "assets-1.9.1".to_string(),
        "assets-1.9.0" => "assets-1.9.0".to_string(),
        "assets-1.8.2" => "assets-1.8.2".to_string(),
        "assets-1.8.1" => "assets-1.8.1".to_string(),
        "assets-1.8.0" => "assets-1.8.0".to_string(),
        "assets-1.7.0" => "assets-1.7.0".to_string(),
        "assets-1.6.0" => "assets-1.6.0".to_string(),
        "assets-1.5.1" => "assets-1.5.1".to_string(),
        "assets-1.5.0" => "assets-1.5.0".to_string(),
        "assets-1.4.2" => "assets-1.4.2".to_string(),
        "assets-1.4.1" => "assets-1.4.1".to_string(),
        "assets-1.4.0" => "assets-1.4.0".to_string(),
        "assets-1.3.3" => "assets-1.3.3".to_string(),
        "assets-1.3.2" => "assets-1.3.2".to_string(),
        "assets-1.3.1" => "assets-1.3.1".to_string(),
        "assets-1.3.0" => "assets-1.3.0".to_string(),
        "assets-1.2.1" => "assets-1.2.1".to_string(),
        "assets-1.2.0" => "assets-1.2.0".to_string(),
        "assets-1.1.0" => "assets-1.1.0".to_string(),
        "assets-1.0.1" => "assets-1.0.1".to_string(),
        "assets-1.0.0" => "assets-1.0.0".to_string(),
        "operations-management-1.10.0" => "operations-management-1.10.0".to_string(),
        "operations-management-1.9.0" => "operations-management-1.9.0".to_string(),
        "operations-management-1.8.1" => "operations-management-1.8.1".to_string(),
        "operations-management-1.8.0" => "operations-management-1.8.0".to_string(),
        "operations-management-1.7.0" => "operations-management-1.7.0".to_string(),
        "operations-management-1.6.0" => "operations-management-1.6.0".to_string(),
        "operations-management-1.5.0" => "operations-management-1.5.0".to_string(),
        "operations-management-1.4.0" => "operations-management-1.4.0".to_string(),
        "operations-management-1.3.0" => "operations-management-1.3.0".to_string(),
        "operations-management-1.2.0" => "operations-management-1.2.0".to_string(),
        "operations-management-1.1.0" => "operations-management-1.1.0".to_string(),
        "operations-management-1.0.0" => "operations-management-1.0.0".to_string(),
        "operations-management-0.2.2" => "operations-management-0.2.2".to_string(),
        "operations-management-0.2.1" => "operations-management-0.2.1".to_string(),
        "operations-management-0.2.0" => "operations-management-0.2.0".to_string(),
        "operations-management-0.1.0" => "operations-management-0.1.0".to_string(),
        "operations-management-0.0.2" => "operations-management-0.0.2".to_string(),
        "operations-management-0.0.1" => "operations-management-0.0.1".to_string(),
        "visitors-2.0.0" => "visitors-2.0.0".to_string(),
        "visitors-1.2.0" => "visitors-1.2.0".to_string(),
        "visitors-1.1.0" => "visitors-1.1.0".to_string(),
        "visitors-1.0.1" => "visitors-1.0.1".to_string(),
        "visitors-1.0.0" => "visitors-1.0.0".to_string(),
        "supporting-files-2.7.11" => "supporting-files-2.7.11".to_string(),
        "supporting-files-2.7.10" => "supporting-files-2.7.10".to_string(),
        "supporting-files-2.7.9" => "supporting-files-2.7.9".to_string(),
        "supporting-files-2.7.8" => "supporting-files-2.7.8".to_string(),
        "supporting-files-2.7.7" => "supporting-files-2.7.7".to_string(),
        "supporting-files-2.7.6" => "supporting-files-2.7.6".to_string(),
        "supporting-files-2.7.5" => "supporting-files-2.7.5".to_string(),
        "supporting-files-2.7.4" => "supporting-files-2.7.4".to_string(),
        "supporting-files-2.7.3" => "supporting-files-2.7.3".to_string(),
        "supporting-files-2.7.2" => "supporting-files-2.7.2".to_string(),
        "supporting-files-2.7.1" => "supporting-files-2.7.1".to_string(),
        "supporting-files-2.7.0" => "supporting-files-2.7.0".to_string(),
        "supporting-files-2.6.0" => "supporting-files-2.6.0".to_string(),
        "supporting-files-2.5.2" => "supporting-files-2.5.2".to_string(),
        "supporting-files-2.5.1" => "supporting-files-2.5.1".to_string(),
        "supporting-files-2.5.0" => "supporting-files-2.5.0".to_string(),
        "supporting-files-1.58.0" => "supporting-files-1.58.0".to_string(),
        "supporting-files-1.57.0" => "supporting-files-1.57.0".to_string(),
        "supporting-files-1.56.0" => "supporting-files-1.56.0".to_string(),
        "supporting-files-1.55.1" => "supporting-files-1.55.1".to_string(),
        "supporting-files-1.55.0" => "supporting-files-1.55.0".to_string(),
        "supporting-files-1.54.0" => "supporting-files-1.54.0".to_string(),
        "supporting-files-1.53.0" => "supporting-files-1.53.0".to_string(),
        "supporting-files-1.52.0" => "supporting-files-1.52.0".to_string(),
        "supporting-files-1.51.0" => "supporting-files-1.51.0".to_string(),
        "supporting-files-1.50.0" => "supporting-files-1.50.0".to_string(),
        "supporting-files-1.49.0" => "supporting-files-1.49.0".to_string(),
        "supporting-files-1.48.0" => "supporting-files-1.48.0".to_string(),
        "supporting-files-1.47.0" => "supporting-files-1.47.0".to_string(),
        "supporting-files-1.46.0" => "supporting-files-1.46.0".to_string(),
        "supporting-files-1.45.0" => "supporting-files-1.45.0".to_string(),
        "supporting-files-1.44.0" => "supporting-files-1.44.0".to_string(),
        "supporting-files-1.43.0" => "supporting-files-1.43.0".to_string(),
        "supporting-files-1.42.0" => "supporting-files-1.42.0".to_string(),
        "supporting-files-1.41.0" => "supporting-files-1.41.0".to_string(),
        "supporting-files-1.40.0" => "supporting-files-1.40.0".to_string(),
        "supporting-files-1.39.0" => "supporting-files-1.39.0".to_string(),
        "supporting-files-1.38.1" => "supporting-files-1.38.1".to_string(),
        "supporting-files-1.38.0" => "supporting-files-1.38.0".to_string(),
        "supporting-files-1.37.0" => "supporting-files-1.37.0".to_string(),
        "supporting-files-1.36.1" => "supporting-files-1.36.1".to_string(),
        "supporting-files-1.36.0" => "supporting-files-1.36.0".to_string(),
        "supporting-files-1.35.1" => "supporting-files-1.35.1".to_string(),
        "supporting-files-1.35.0" => "supporting-files-1.35.0".to_string(),
        "supporting-files-1.34.0" => "supporting-files-1.34.0".to_string(),
        "supporting-files-1.33.1" => "supporting-files-1.33.1".to_string(),
        "supporting-files-1.33.0" => "supporting-files-1.33.0".to_string(),
        "supporting-files-1.32.0" => "supporting-files-1.32.0".to_string(),
        "supporting-files-1.31.0" => "supporting-files-1.31.0".to_string(),
        "supporting-files-1.30.1" => "supporting-files-1.30.1".to_string(),
        "supporting-files-1.30.0" => "supporting-files-1.30.0".to_string(),
        "supporting-files-1.29.0" => "supporting-files-1.29.0".to_string(),
        "supporting-files-1.28.0" => "supporting-files-1.28.0".to_string(),
        "supporting-files-1.27.0" => "supporting-files-1.27.0".to_string(),
        "supporting-files-1.26.0" => "supporting-files-1.26.0".to_string(),
        "supporting-files-1.25.0" => "supporting-files-1.25.0".to_string(),
        "supporting-files-1.24.0" => "supporting-files-1.24.0".to_string(),
        "supporting-files-1.23.0" => "supporting-files-1.23.0".to_string(),
        "supporting-files-1.22.0" => "supporting-files-1.22.0".to_string(),
        "supporting-files-1.21.0" => "supporting-files-1.21.0".to_string(),
        "supporting-files-1.20.0" => "supporting-files-1.20.0".to_string(),
        "supporting-files-1.19.0" => "supporting-files-1.19.0".to_string(),
        "supporting-files-1.18.0" => "supporting-files-1.18.0".to_string(),
        "supporting-files-1.17.1" => "supporting-files-1.17.1".to_string(),
        "supporting-files-1.17.0" => "supporting-files-1.17.0".to_string(),
        "supporting-files-1.16.0" => "supporting-files-1.16.0".to_string(),
        "supporting-files-1.15.1" => "supporting-files-1.15.1".to_string(),
        "supporting-files-1.15.0" => "supporting-files-1.15.0".to_string(),
        "supporting-files-1.14.0" => "supporting-files-1.14.0".to_string(),
        "supporting-files-1.13.0" => "supporting-files-1.13.0".to_string(),
        "supporting-files-1.12.0" => "supporting-files-1.12.0".to_string(),
        "supporting-files-1.11.0" => "supporting-files-1.11.0".to_string(),
        "supporting-files-1.10.0" => "supporting-files-1.10.0".to_string(),
        "supporting-files-1.9.0" => "supporting-files-1.9.0".to_string(),
        "supporting-files-1.8.0" => "supporting-files-1.8.0".to_string(),
        "supporting-files-1.7.3" => "supporting-files-1.7.3".to_string(),
        "supporting-files-1.7.2" => "supporting-files-1.7.2".to_string(),
        "supporting-files-1.7.1" => "supporting-files-1.7.1".to_string(),
        "supporting-files-1.7.0" => "supporting-files-1.7.0".to_string(),
        "supporting-files-1.6.0" => "supporting-files-1.6.0".to_string(),
        "supporting-files-1.5.0" => "supporting-files-1.5.0".to_string(),
        "supporting-files-1.4.0" => "supporting-files-1.4.0".to_string(),
        "supporting-files-1.3.0" => "supporting-files-1.3.0".to_string(),
        "supporting-files-1.2.0" => "supporting-files-1.2.0".to_string(),
        "supporting-files-1.1.0" => "supporting-files-1.1.0".to_string(),
        "supporting-files-1.0.0" => "supporting-files-1.0.0".to_string(),
        "supporting-files-0.0.2" => "supporting-files-0.0.2".to_string(),
        "supporting-files-0.0.1" => "supporting-files-0.0.1".to_string(),
        "access-roles-saas" => "access-roles-saas".to_string(),
        "access-roles-va-release-1-2022" => "access-roles-va-release-1-2022".to_string(),
        "access-roles-va-release-2-2022" => "access-roles-va-release-2-2022".to_string(),
        "access-roles-va-release-3-2022" => "access-roles-va-release-3-2022".to_string(),
        "access-roles-va-release-1-2023" => "access-roles-va-release-1-2023".to_string(),
        "access-roles-va-release-2-2023" => "access-roles-va-release-2-2023".to_string(),
        "access-roles-va-release-3-2023" => "access-roles-va-release-3-2023".to_string(),
        "access-roles-va-release-1-2024" => "access-roles-va-release-1-2024".to_string(),
        "access-roles-va-release-2-2024" => "access-roles-va-release-2-2024".to_string(),
        "access-roles-va-release-3-2024" => "access-roles-va-release-3-2024".to_string(),
        "access-roles-va-release-4-2024" => "access-roles-va-release-4-2024".to_string(),
        "access-roles-va-release-1-2025" => "access-roles-va-release-1-2025".to_string(),
        "access-roles-va-release-2-2025" => "access-roles-va-release-2-2025".to_string(),
        "access-roles-va-release-3-2025" => "access-roles-va-release-3-2025".to_string(),
        "access-roles-va-release-4-2025" => "access-roles-va-release-4-2025".to_string(),
        "access-roles-va-release-1-2026" => "access-roles-va-release-1-2026".to_string(),
        "lookandfeel-1.0.0" => "lookandfeel-1.0.0".to_string(),
        "task-notifications-1.0.0" => "task-notifications-1.0.0".to_string(),
        "settings-1.1.0" => "settings-1.1.0".to_string(),
        "settings-1.0.0" => "settings-1.0.0".to_string(),
        "custom-action-support-saas" => "custom-action-support-saas".to_string(),
        "custom-action-support-va-release-1-2021" => "custom-action-support-va-release-1-2021".to_string(),
        "custom-action-support-va-release-2-2021" => "custom-action-support-va-release-2-2021".to_string(),
        "custom-action-support-va-release-3-2021" => "custom-action-support-va-release-3-2021".to_string(),
        "custom-action-support-va-release-4-2021" => "custom-action-support-va-release-4-2021".to_string(),
        "custom-action-support-va-release-1-2022" => "custom-action-support-va-release-1-2022".to_string(),
        "custom-action-support-va-release-2-2022" => "custom-action-support-va-release-2-2022".to_string(),
        "custom-action-support-va-release-3-2022" => "custom-action-support-va-release-3-2022".to_string(),
        "custom-action-support-va-release-1-2023-or-newer" => "custom-action-support-va-release-1-2023-or-newer".to_string(),
        other => other.to_string(),
    })
}
// mcpify:versions:end

async fn prompt_transport() -> anyhow::Result<Transport> {
    let choices = vec![
        "stdio (spawned as a subprocess by the MCP client)",
        "http (a standalone server the MCP client connects to over the network)",
    ];
    let selection = tokio::task::spawn_blocking(move || {
        inquire::Select::new("Which transport will this deployment use?", choices).prompt()
    })
    .await??;

    Ok(if selection.starts_with("stdio") {
        Transport::Stdio
    } else {
        Transport::Http
    })
}

async fn prompt_credentials(auth_method: AuthMethod) -> anyhow::Result<HashMap<String, String>> {
    tokio::task::spawn_blocking(move || -> anyhow::Result<HashMap<String, String>> {
        let mut credentials = HashMap::new();
        match auth_method {
            AuthMethod::Basic => {
                credentials.insert(
                    "username".to_string(),
                    inquire::Text::new("Username:")
                        .with_help_message("Your TOPdesk login name.")
                        .prompt()?,
                );
                credentials.insert(
                    "password".to_string(),
                    inquire::Password::new("Password (application token):")
                        .with_help_message(
                            "TOPdesk's REST API authenticates with an application token, not your web-interface password — generate one in TOPdesk under your profile's Application Passwords.",
                        )
                        .without_confirmation()
                        .prompt()?,
                );
            }
        }
        Ok(credentials)
    })
    .await?
}

async fn prompt_persistence(env: &HashMap<String, String>) -> anyhow::Result<()> {
    let choices = vec![
        "Write a .env file",
        "Write a config.json file",
        "Print a ready-to-run CLI invocation (nothing written to disk)",
    ];
    let selection = tokio::task::spawn_blocking(move || {
        inquire::Select::new("How should these settings be saved?", choices).prompt()
    })
    .await??;

    match selection {
        "Write a .env file" => {
            let contents = env
                .iter()
                .map(|(key, value)| format!("{key}={value}"))
                .collect::<Vec<_>>()
                .join("\n");
            std::fs::write(".env", format!("{contents}\n"))?;
            println!("Wrote .env");
        }
        "Write a config.json file" => {
            std::fs::write("config.json", serde_json::to_string_pretty(env)?)?;
            println!("Wrote config.json");
        }
        _ => {
            let flags = env
                .iter()
                .map(|(key, value)| {
                    format!("--{} {:?}", key.to_lowercase().replace('_', "-"), value)
                })
                .collect::<Vec<_>>()
                .join(" ");
            println!("topdesk-mcp start {flags}");
        }
    }
    Ok(())
}

/// Prints a ready-to-use MCP client config (the `mcpServers` block a host
/// like Claude Code/Desktop expects) for whichever transport was selected
/// — the stdio and http shapes are mutually exclusive, never both, since
/// they're two different ways of running this same server and a client
/// only ever picks one. HTTP transport shows credentials as headers only
/// (never env/CLI args, matching `AuthManager::apply_auth_headers`'s
/// HTTP-only-uses-per-request-credentials behavior); stdio shows both the
/// `env` block and the equivalent all-CLI-args invocation, since the
/// config cascade accepts either for a spawned subprocess.
fn print_mcp_client_config(
    transport: Transport,
    auth_method: AuthMethod,
    env: &HashMap<String, String>,
) {
    match transport {
        Transport::Stdio => {
            let config = serde_json::json!({
                "mcpServers": {
                    "topdesk-mcp": {
                        "command": "topdesk-mcp",
                        "args": ["start"],
                        "env": env,
                    }
                }
            });
            println!("\nMCP client config (stdio):");
            println!("{}", serde_json::to_string_pretty(&config).unwrap());

            let cli_args = env
                .iter()
                .map(|(key, value)| format!("--{} {value:?}", key.to_lowercase().replace('_', "-")))
                .collect::<Vec<_>>()
                .join(" ");
            println!("(equivalently: `topdesk-mcp start {cli_args}`)");
        }
        Transport::Http => {
            let (_, header_name) =
                topdesk_mcp::auth::auth_manager::header_location_for(auth_method);
            let mut headers = serde_json::Map::new();
            headers.insert(
                header_name.to_string(),
                serde_json::Value::String("<credential value here>".to_string()),
            );
            let config = serde_json::json!({
                "mcpServers": {
                    "topdesk-mcp": {
                        "url": "http://127.0.0.1:3000/mcp",
                        "headers": headers,
                    }
                }
            });
            println!(
                "\nMCP client config (http) — adjust the host/port to match how you run \
                 `topdesk-mcp http`:"
            );
            println!("{}", serde_json::to_string_pretty(&config).unwrap());
            println!(
                "Credentials are never read from local config/env over HTTP transport — \
                 every request must carry its own \"{header_name}\" header."
            );
        }
    }
}

pub async fn run_setup_wizard() -> anyhow::Result<()> {
    let url = prompt_base_url().await?;
    let auth_method = prompt_auth_method().await?;
    let credentials = prompt_credentials(auth_method).await?;
    let api_version = prompt_api_version().await?;
    let transport = prompt_transport().await?;

    save_credential("active-credentials", &serde_json::to_string(&credentials)?)?;

    let mut env: HashMap<String, String> = HashMap::new();
    env.insert("TOPDESK_MCP_URL".to_string(), url);
    env.insert(
        "TOPDESK_MCP_AUTH_METHOD".to_string(),
        serde_json::to_value(auth_method)?
            .as_str()
            .unwrap_or_default()
            .to_string(),
    );
    env.insert("TOPDESK_MCP_API_VERSION".to_string(), api_version);
    env.insert(
        "TOPDESK_MCP_TRANSPORT".to_string(),
        serde_json::to_value(transport)?
            .as_str()
            .unwrap_or_default()
            .to_string(),
    );
    for (key, value) in &credentials {
        env.insert(format!("TOPDESK_MCP_{}", to_env_key(key)), value.clone());
    }

    prompt_persistence(&env).await?;
    print_mcp_client_config(transport, auth_method, &env);

    let run_command = match transport {
        Transport::Stdio => "start",
        Transport::Http => "http",
    };
    println!("Setup complete! Run: topdesk-mcp {run_command}");
    Ok(())
}
