// General API MCP server — generated by mcpify. Do not hand-edit.
//
// v8 multi-version support: lists the OpenAPI spec versions this project
// currently has a store for (added at `generate`/`mcpify add-version` time),
// showing which is the default/latest and which is active for this process.

use topdesk_mcp::core::config_manager::load_config;

struct VersionRow {
    label: &'static str,
    is_default: bool,
}

// mcpify:versions:begin
const KNOWN_VERSIONS: &[VersionRow] = &[
    VersionRow {
        label: "general-1.2.0",
        is_default: true,
    },
    VersionRow {
        label: "general-1.1.1",
        is_default: false,
    },
    VersionRow {
        label: "general-1.1.0",
        is_default: false,
    },
    VersionRow {
        label: "general-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "incident-4.2.6",
        is_default: false,
    },
    VersionRow {
        label: "incident-4.2.5",
        is_default: false,
    },
    VersionRow {
        label: "incident-4.2.4",
        is_default: false,
    },
    VersionRow {
        label: "incident-4.2.3",
        is_default: false,
    },
    VersionRow {
        label: "incident-4.2.2",
        is_default: false,
    },
    VersionRow {
        label: "incident-4.2.1",
        is_default: false,
    },
    VersionRow {
        label: "incident-4.2.0",
        is_default: false,
    },
    VersionRow {
        label: "incident-4.1.0",
        is_default: false,
    },
    VersionRow {
        label: "incident-4.0.0",
        is_default: false,
    },
    VersionRow {
        label: "incident-3.9.1",
        is_default: false,
    },
    VersionRow {
        label: "incident-3.9.0",
        is_default: false,
    },
    VersionRow {
        label: "incident-3.8.5",
        is_default: false,
    },
    VersionRow {
        label: "incident-3.8.4",
        is_default: false,
    },
    VersionRow {
        label: "incident-3.8.3",
        is_default: false,
    },
    VersionRow {
        label: "incident-3.8.2",
        is_default: false,
    },
    VersionRow {
        label: "incident-3.8.1",
        is_default: false,
    },
    VersionRow {
        label: "incident-3.8.0",
        is_default: false,
    },
    VersionRow {
        label: "incident-3.7.1",
        is_default: false,
    },
    VersionRow {
        label: "knowledge-base-before-explorer-migration",
        is_default: false,
    },
    VersionRow {
        label: "knowledge-base-after-explorer-migration",
        is_default: false,
    },
    VersionRow {
        label: "knowledgebase-graphql-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-2.0.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.23.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.22.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.21.1",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.21.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.20.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.19.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.18.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.17.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.16.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.15.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.14.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.13.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.12.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.11.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.10.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.9.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.8.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.7.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.6.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.5.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.4.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.3.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.2.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.1.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "services-1.3.7",
        is_default: false,
    },
    VersionRow {
        label: "services-1.3.6",
        is_default: false,
    },
    VersionRow {
        label: "services-1.3.5",
        is_default: false,
    },
    VersionRow {
        label: "services-1.3.4",
        is_default: false,
    },
    VersionRow {
        label: "services-1.3.3",
        is_default: false,
    },
    VersionRow {
        label: "services-1.3.2",
        is_default: false,
    },
    VersionRow {
        label: "services-1.3.1",
        is_default: false,
    },
    VersionRow {
        label: "services-1.3.0",
        is_default: false,
    },
    VersionRow {
        label: "services-1.2.0",
        is_default: false,
    },
    VersionRow {
        label: "services-1.1.0",
        is_default: false,
    },
    VersionRow {
        label: "services-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "change-1.4.0",
        is_default: false,
    },
    VersionRow {
        label: "change-1.3.7",
        is_default: false,
    },
    VersionRow {
        label: "change-1.3.6",
        is_default: false,
    },
    VersionRow {
        label: "change-1.3.5",
        is_default: false,
    },
    VersionRow {
        label: "change-1.3.4",
        is_default: false,
    },
    VersionRow {
        label: "change-1.3.3",
        is_default: false,
    },
    VersionRow {
        label: "change-1.3.2",
        is_default: false,
    },
    VersionRow {
        label: "change-1.3.1",
        is_default: false,
    },
    VersionRow {
        label: "change-1.3.0",
        is_default: false,
    },
    VersionRow {
        label: "change-1.2.5",
        is_default: false,
    },
    VersionRow {
        label: "change-1.2.4",
        is_default: false,
    },
    VersionRow {
        label: "change-1.2.3",
        is_default: false,
    },
    VersionRow {
        label: "change-1.2.2",
        is_default: false,
    },
    VersionRow {
        label: "change-1.2.1",
        is_default: false,
    },
    VersionRow {
        label: "change-1.2.0",
        is_default: false,
    },
    VersionRow {
        label: "change-1.1.4",
        is_default: false,
    },
    VersionRow {
        label: "change-1.1.3",
        is_default: false,
    },
    VersionRow {
        label: "change-1.1.2",
        is_default: false,
    },
    VersionRow {
        label: "change-1.1.1",
        is_default: false,
    },
    VersionRow {
        label: "change-1.1.0",
        is_default: false,
    },
    VersionRow {
        label: "change-1.0.2",
        is_default: false,
    },
    VersionRow {
        label: "change-1.0.1",
        is_default: false,
    },
    VersionRow {
        label: "change-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.91.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.91.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.90.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.89.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.88.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.87.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.86.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.85.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.84.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.83.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.82.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.81.5",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.81.4",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.81.3",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.81.2",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.81.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.81.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.80.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.79.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.79.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.78.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.77.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.76.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.75.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.74.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.73.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.72.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.71.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.70.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.69.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.68.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.67.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.67.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.66.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.65.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.64.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.63.2",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.63.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.63.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.62.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.61.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.60.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.59.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.59.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.58.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.57.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.56.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.55.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.54.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.53.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.52.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.52.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.51.3",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.51.2",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.51.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.51.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.50.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.50.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.49.2",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.49.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.49.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.48.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.47.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.46.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.46.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.45.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.44.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.43.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.42.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.41.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.40.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.39.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.38.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.37.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.36.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.36.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.35.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.35.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.34.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.33.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.32.2",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.32.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.32.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.31.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.30.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.29.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.28.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.27.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.26.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.25.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.25.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.24.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.23.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.22.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.22.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.21.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.20.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.19.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.18.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.17.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.16.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.15.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.14.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.13.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.12.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.11.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.10.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.9.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.9.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.8.2",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.8.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.8.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.7.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.6.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.5.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.5.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.4.2",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.4.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.4.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.3.3",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.3.2",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.3.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.3.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.2.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.2.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.1.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.0.1",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.10.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.9.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.8.1",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.8.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.7.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.6.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.5.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.4.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.3.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.2.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.1.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-0.2.2",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-0.2.1",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-0.2.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-0.1.0",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-0.0.2",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-0.0.1",
        is_default: false,
    },
    VersionRow {
        label: "visitors-2.0.0",
        is_default: false,
    },
    VersionRow {
        label: "visitors-1.2.0",
        is_default: false,
    },
    VersionRow {
        label: "visitors-1.1.0",
        is_default: false,
    },
    VersionRow {
        label: "visitors-1.0.1",
        is_default: false,
    },
    VersionRow {
        label: "visitors-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.11",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.10",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.9",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.8",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.7",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.6",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.5",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.4",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.3",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.2",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.1",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.6.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.5.2",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.5.1",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.5.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.58.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.57.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.56.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.55.1",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.55.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.54.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.53.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.52.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.51.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.50.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.49.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.48.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.47.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.46.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.45.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.44.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.43.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.42.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.41.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.40.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.39.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.38.1",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.38.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.37.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.36.1",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.36.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.35.1",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.35.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.34.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.33.1",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.33.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.32.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.31.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.30.1",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.30.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.29.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.28.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.27.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.26.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.25.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.24.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.23.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.22.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.21.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.20.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.19.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.18.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.17.1",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.17.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.16.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.15.1",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.15.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.14.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.13.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.12.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.11.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.10.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.9.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.8.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.7.3",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.7.2",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.7.1",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.7.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.6.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.5.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.4.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.3.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.2.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.1.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-0.0.2",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-0.0.1",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-saas",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-1-2022",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-2-2022",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-3-2022",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-1-2023",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-2-2023",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-3-2023",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-1-2024",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-2-2024",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-3-2024",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-4-2024",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-1-2025",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-2-2025",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-3-2025",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-4-2025",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-1-2026",
        is_default: false,
    },
    VersionRow {
        label: "lookandfeel-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "task-notifications-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "settings-1.1.0",
        is_default: false,
    },
    VersionRow {
        label: "settings-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "custom-action-support-saas",
        is_default: false,
    },
    VersionRow {
        label: "custom-action-support-va-release-1-2021",
        is_default: false,
    },
    VersionRow {
        label: "custom-action-support-va-release-2-2021",
        is_default: false,
    },
    VersionRow {
        label: "custom-action-support-va-release-3-2021",
        is_default: false,
    },
    VersionRow {
        label: "custom-action-support-va-release-4-2021",
        is_default: false,
    },
    VersionRow {
        label: "custom-action-support-va-release-1-2022",
        is_default: false,
    },
    VersionRow {
        label: "custom-action-support-va-release-2-2022",
        is_default: false,
    },
    VersionRow {
        label: "custom-action-support-va-release-3-2022",
        is_default: false,
    },
    VersionRow {
        label: "custom-action-support-va-release-1-2023-or-newer",
        is_default: false,
    },
];
// mcpify:versions:end

pub fn run() -> anyhow::Result<()> {
    let active_version = load_config(serde_json::Map::new())
        .map(|config| config.api_version)
        .unwrap_or_default();

    for row in KNOWN_VERSIONS {
        let mut markers = Vec::new();
        if row.is_default {
            markers.push("default");
        }
        if row.label == active_version {
            markers.push("active");
        }
        if markers.is_empty() {
            println!("{}", row.label);
        } else {
            println!("{} ({})", row.label, markers.join(", "));
        }
    }
    Ok(())
}
