// General API MCP server — generated by mcpify. Do not hand-edit.
//
// v8 multi-version support: lists the OpenAPI spec versions this project
// currently has a store for (added at `generate`/`mcpify add-version` time),
// showing which is the default/latest and which is active for this process.

use topdesk_mcp::core::config_manager::load_config;

struct VersionRow {
    label: &'static str,
    is_default: bool,
}

// mcpify:versions:begin
const KNOWN_VERSIONS: &[VersionRow] = &[
    VersionRow {
        label: "general-1.2.0",
        is_default: true,
    },
    VersionRow {
        label: "incident-4.2.6",
        is_default: false,
    },
    VersionRow {
        label: "knowledge-base-before-explorer-migration",
        is_default: false,
    },
    VersionRow {
        label: "knowledge-base-after-explorer-migration",
        is_default: false,
    },
    VersionRow {
        label: "knowledgebase-graphql-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "reservations-2.0.0",
        is_default: false,
    },
    VersionRow {
        label: "services-1.3.7",
        is_default: false,
    },
    VersionRow {
        label: "change-1.4.0",
        is_default: false,
    },
    VersionRow {
        label: "assets-1.91.1",
        is_default: false,
    },
    VersionRow {
        label: "operations-management-1.10.0",
        is_default: false,
    },
    VersionRow {
        label: "visitors-2.0.0",
        is_default: false,
    },
    VersionRow {
        label: "supporting-files-2.7.11",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-saas",
        is_default: false,
    },
    VersionRow {
        label: "access-roles-va-release-1-2026",
        is_default: false,
    },
    VersionRow {
        label: "lookandfeel-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "task-notifications-1.0.0",
        is_default: false,
    },
    VersionRow {
        label: "settings-1.1.0",
        is_default: false,
    },
    VersionRow {
        label: "custom-action-support-saas",
        is_default: false,
    },
    VersionRow {
        label: "custom-action-support-va-release-1-2023-or-newer",
        is_default: false,
    },
];
// mcpify:versions:end

pub fn run() -> anyhow::Result<()> {
    let active_version = load_config(serde_json::Map::new())
        .map(|config| config.api_version)
        .unwrap_or_default();

    for row in KNOWN_VERSIONS {
        let mut markers = Vec::new();
        if row.is_default {
            markers.push("default");
        }
        if row.label == active_version {
            markers.push("active");
        }
        if markers.is_empty() {
            println!("{}", row.label);
        } else {
            println!("{} ({})", row.label, markers.join(", "));
        }
    }
    Ok(())
}
