// General API MCP server — generated by mcpify. Do not hand-edit.

#[derive(Debug, Clone)]
pub struct HttpServerConfig {
    pub host: String,
    pub port: u16,
    pub cors_allow: Option<String>,
}
