// General API MCP server — generated by mcpify. Do not hand-edit.

use std::io::IsTerminal;

/// Pretty-printed to an interactive TTY, structured JSON otherwise
/// (containers/CI) — mirrors `targets::typescript`'s `log-transport.ts`
/// TTY-detection logic.
pub fn use_pretty_output() -> bool {
    std::io::stdout().is_terminal()
}
