// General API MCP server — generated by mcpify. Do not hand-edit.

use std::io::IsTerminal;

/// Pretty-printed to an interactive TTY, structured JSON otherwise
/// (containers/CI) — mirrors `targets::typescript`'s `log-transport.ts`
/// TTY-detection logic. Checks stderr, not stdout: that's where logs are
/// actually written (see `logger::init_logging`), since stdout is reserved
/// for the MCP stdio transport's JSON-RPC frames.
pub fn use_pretty_output() -> bool {
    std::io::stderr().is_terminal()
}
