// Hand-authored — MCP prompts capability. Not generated by mcpify; a
// regeneration will not touch this module, but see
// docs/mcp-prompts-workflow-plan.md before running one.

use rmcp::schemars;
use serde::Deserialize;

mod router;

/// Shared argument struct for every guided domain-workflow prompt (see
/// `router.rs`). `context` is `Option` rather than required: MCP prompt
/// arguments are conventionally collected up front by whatever UI a
/// client renders, which doesn't suit values that only become known
/// partway through a guided flow — "ask if missing" lives in each
/// prompt's instructional prose instead of transport-level validation.
#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct WorkflowArgs {
    /// Anything you already know going in: a ticket/record number,
    /// current step, environment, or other context. Leave unset if
    /// starting fresh.
    pub context: Option<String>,
}

/// Renders the "is the right catalog even loaded" preamble every guided
/// domain-workflow prompt opens with. `McpifyServer` only ever has one
/// `api_version` catalog active per process (config-time, not
/// switchable mid-session), so a workflow prompt written for e.g.
/// `change-1.4.0` is silently useless if the operator actually started
/// the server with a different catalog active. Stating this in
/// ground-truth terms up front (known at construction time, zero tool
/// round-trips) avoids the calling LLM wasting a `search` call
/// discovering the mismatch the hard way, or worse, inventing an
/// operationId when `search` comes back empty.
pub(crate) fn catalog_check_block(active_api_version: &str, expected: &[&str]) -> String {
    let expected_list = expected.join("`, `");
    if expected.contains(&active_api_version) {
        format!(
            "## Active catalog check\n\n\
             Active catalog: `{active_api_version}` — matches what this workflow needs \
             (one of `{expected_list}`). You can proceed, but individual operation \
             names below still aren't guaranteed to exist verbatim in this exact \
             version — confirm each one with `search`/`get` before calling it.\n"
        )
    } else {
        format!(
            "## Active catalog check — MISMATCH\n\n\
             Active catalog: `{active_api_version}`. This workflow needs one of: \
             `{expected_list}`.\n\n\
             Do not proceed as if this workflow's operations exist — they are not in \
             the currently loaded catalog and `search` will not find them. Tell the \
             user plainly that this server needs to be restarted with a different \
             `api_version` (config file or `TOPDESK_MCP_API_VERSION` env var) before \
             this workflow is possible; you cannot switch it yourself mid-session. \
             See docs/SCHEMA_VERSIONS.md for the exact version label to use.\n"
        )
    }
}

/// Renders the "context already provided" header from the optional
/// `WorkflowArgs.context` field — empty string if `None` or blank, so
/// callers that never populate prompt arguments (most agentic clients)
/// don't get a dangling empty section.
pub(crate) fn render_context_header(context: Option<&str>) -> String {
    match context.map(str::trim) {
        Some(text) if !text.is_empty() => {
            format!("## Context already provided\n\n{text}\n\n")
        }
        _ => String::new(),
    }
}

/// Static delegation/parallelization guidance appended to every prompt —
/// phrased conditionally since not every MCP client has a sub-task
/// mechanism. Whole-workflow delegation is the primary lever for saving
/// context/tokens; step-level delegation/parallelization is the
/// finer-grained complement for individual verbose steps.
pub(crate) fn delegation_guidance() -> &'static str {
    "\n## If your environment supports delegation\n\n\
     Some MCP clients can hand work to a sub-task/sub-agent with its own \
     context window (e.g. a Task tool, background agent). If yours does:\n\n\
     - **Whole-workflow delegation** (biggest context saving): once the \
       catalog check above passes, hand this entire playbook to a sub-task \
       and only bring back the outcome (record number, status, any \
       question that needs a human decision) — not every intermediate \
       search/get/call round-trip.\n\
     - **Step-level delegation**, even without the above: large searches \
       (enumerating every category/operator/branch), and independent bulk \
       calls with no ordering dependency between them (e.g. registering \
       several unrelated assets), are good candidates to delegate or run \
       in parallel rather than piping every raw row through your own \
       context.\n\n\
     If your environment has no such mechanism, just work the numbered \
     steps directly in this conversation — none of the above is required \
     for correctness, only for context budget.\n"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_check_block_matches_when_active_version_is_expected() {
        let block = catalog_check_block("change-1.4.0", &["change-1.4.0"]);
        assert!(block.contains("Active catalog check\n"));
        assert!(!block.contains("MISMATCH"));
        assert!(!block.contains("restart"));
    }

    #[test]
    fn catalog_check_block_flags_mismatch_with_restart_guidance() {
        let block = catalog_check_block("general-1.2.0", &["change-1.4.0", "incident-4.2.6"]);
        assert!(block.contains("MISMATCH"));
        assert!(block.contains("general-1.2.0"));
        assert!(block.contains("change-1.4.0"));
        assert!(block.contains("incident-4.2.6"));
        assert!(block.contains("restart"));
    }

    #[test]
    fn render_context_header_handles_every_shape() {
        assert_eq!(render_context_header(None), "");
        assert_eq!(render_context_header(Some("")), "");
        assert_eq!(render_context_header(Some("   ")), "");
        let rendered = render_context_header(Some("CHG-123 already drafted"));
        assert!(rendered.contains("Context already provided"));
        assert!(rendered.contains("CHG-123 already drafted"));
    }

    #[test]
    fn delegation_guidance_mentions_whole_workflow_delegation() {
        assert!(delegation_guidance().contains("Whole-workflow delegation"));
    }
}
