// Hand-authored — MCP prompts capability. Not generated by mcpify; a
// regeneration will not touch this module, but see
// docs/mcp-prompts-workflow-plan.md before running one.

use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{PromptMessage, Role};
use rmcp::{prompt, prompt_router};

use crate::core::mcp_server::McpifyServer;
use crate::prompts::{
    WorkflowArgs, catalog_check_block, delegation_guidance, render_context_header,
};

// `vis = "pub(crate)"`: the generated `prompt_router()` associated fn
// defaults to private-to-this-module (`Visibility::Inherited`), but
// `McpifyServer::new()` in `core::mcp_server` — a different module —
// needs to call it, the same way `#[tool_router]`'s equivalent fn is
// called from that same constructor.
#[prompt_router(vis = "pub(crate)")]
impl McpifyServer {
    #[prompt(
        name = "topdesk-menu",
        description = "Directory of every guided TOPdesk workflow prompt this server offers, plus which API-version catalog each one needs."
    )]
    async fn topdesk_menu(&self) -> Vec<PromptMessage> {
        let body = format!(
            "Active catalog right now: `{}`\n\n{}\n{}",
            self.api_version(),
            include_str!("content/menu.md"),
            delegation_guidance(),
        );
        vec![PromptMessage::new_text(Role::User, body)]
    }

    #[prompt(
        name = "topdesk-change-management-lifecycle",
        description = "Guided RFC lifecycle for TOPdesk Change Management: classification, planning, CAB approval routing, implementation, and closure."
    )]
    async fn change_management_lifecycle(
        &self,
        Parameters(args): Parameters<WorkflowArgs>,
    ) -> Vec<PromptMessage> {
        let body = format!(
            "{}{}{}\n{}",
            catalog_check_block(self.api_version(), &["change-1.4.0"]),
            render_context_header(args.context.as_deref()),
            include_str!("content/change_management_lifecycle.md"),
            delegation_guidance(),
        );
        vec![PromptMessage::new_text(Role::User, body)]
    }

    #[prompt(
        name = "topdesk-incident-lifecycle",
        description = "Guided TOPdesk Incident lifecycle: create, classify, assign, escalate to major incident, communicate, resolve, and close."
    )]
    async fn incident_lifecycle(
        &self,
        Parameters(args): Parameters<WorkflowArgs>,
    ) -> Vec<PromptMessage> {
        let body = format!(
            "{}{}{}\n{}",
            catalog_check_block(self.api_version(), &["incident-4.2.6"]),
            render_context_header(args.context.as_deref()),
            include_str!("content/incident_lifecycle.md"),
            delegation_guidance(),
        );
        vec![PromptMessage::new_text(Role::User, body)]
    }

    #[prompt(
        name = "topdesk-asset-management-basics",
        description = "Register, link, query, and decommission TOPdesk assets."
    )]
    async fn asset_management_basics(
        &self,
        Parameters(args): Parameters<WorkflowArgs>,
    ) -> Vec<PromptMessage> {
        let body = format!(
            "{}{}{}\n{}",
            catalog_check_block(self.api_version(), &["assets-1.91.1"]),
            render_context_header(args.context.as_deref()),
            include_str!("content/asset_management_basics.md"),
            delegation_guidance(),
        );
        vec![PromptMessage::new_text(Role::User, body)]
    }

    #[prompt(
        name = "topdesk-knowledge-base-lifecycle",
        description = "Guided Knowledge Base article lifecycle: draft, review, publish, maintain, and retire, across TOPdesk's REST and GraphQL KB variants."
    )]
    async fn knowledge_base_lifecycle(
        &self,
        Parameters(args): Parameters<WorkflowArgs>,
    ) -> Vec<PromptMessage> {
        let body = format!(
            "{}{}{}\n{}",
            catalog_check_block(
                self.api_version(),
                &[
                    "knowledge-base-before-explorer-migration",
                    "knowledge-base-after-explorer-migration",
                    "knowledgebase-graphql-1.0.0",
                ],
            ),
            render_context_header(args.context.as_deref()),
            include_str!("content/knowledge_base_lifecycle.md"),
            delegation_guidance(),
        );
        vec![PromptMessage::new_text(Role::User, body)]
    }

    #[prompt(
        name = "topdesk-reservations-booking",
        description = "Book, check availability, modify, and cancel TOPdesk reservable resources (rooms, equipment, and more)."
    )]
    async fn reservations_booking(
        &self,
        Parameters(args): Parameters<WorkflowArgs>,
    ) -> Vec<PromptMessage> {
        let body = format!(
            "{}{}{}\n{}",
            catalog_check_block(self.api_version(), &["reservations-2.0.0"]),
            render_context_header(args.context.as_deref()),
            include_str!("content/reservations_booking.md"),
            delegation_guidance(),
        );
        vec![PromptMessage::new_text(Role::User, body)]
    }

    #[prompt(
        name = "topdesk-reference-data-lookup",
        description = "Resolve TOPdesk operator/person/branch/category IDs by name — a lookup catalog referenced by other guided workflows."
    )]
    async fn reference_data_lookup(
        &self,
        Parameters(args): Parameters<WorkflowArgs>,
    ) -> Vec<PromptMessage> {
        let body = format!(
            "{}{}{}\n{}",
            catalog_check_block(self.api_version(), &["supporting-files-2.7.11"]),
            render_context_header(args.context.as_deref()),
            include_str!("content/reference_data_lookup.md"),
            delegation_guidance(),
        );
        vec![PromptMessage::new_text(Role::User, body)]
    }

    #[prompt(
        name = "topdesk-visitor-registration",
        description = "Register, check in, and check out a TOPdesk visitor."
    )]
    async fn visitor_registration(
        &self,
        Parameters(args): Parameters<WorkflowArgs>,
    ) -> Vec<PromptMessage> {
        let body = format!(
            "{}{}{}\n{}",
            catalog_check_block(self.api_version(), &["visitors-2.0.0"]),
            render_context_header(args.context.as_deref()),
            include_str!("content/visitor_registration.md"),
            delegation_guidance(),
        );
        vec![PromptMessage::new_text(Role::User, body)]
    }

    #[prompt(
        name = "topdesk-operations-management-tasks",
        description = "Operational checklists and tasks in TOPdesk Operations Management, including a change's execution checklist."
    )]
    async fn operations_management_tasks(
        &self,
        Parameters(args): Parameters<WorkflowArgs>,
    ) -> Vec<PromptMessage> {
        let body = format!(
            "{}{}{}\n{}",
            catalog_check_block(self.api_version(), &["operations-management-1.10.0"]),
            render_context_header(args.context.as_deref()),
            include_str!("content/operations_management_tasks.md"),
            delegation_guidance(),
        );
        vec![PromptMessage::new_text(Role::User, body)]
    }

    #[prompt(
        name = "topdesk-access-roles-assignment",
        description = "Report on TOPdesk access roles and who holds them (read-only), across the SaaS and Versatile/on-prem API variants."
    )]
    async fn access_roles_assignment(
        &self,
        Parameters(args): Parameters<WorkflowArgs>,
    ) -> Vec<PromptMessage> {
        let body = format!(
            "{}{}{}\n{}",
            catalog_check_block(
                self.api_version(),
                &["access-roles-saas", "access-roles-va-release-1-2026"],
            ),
            render_context_header(args.context.as_deref()),
            include_str!("content/access_roles_assignment.md"),
            delegation_guidance(),
        );
        vec![PromptMessage::new_text(Role::User, body)]
    }

    #[prompt(
        name = "topdesk-self-service-portal-requests",
        description = "Guided Self-Service Portal (SSP) requester workflows: a person creating or tracking their own incident, change, or reservation, across whichever of those catalogs is active."
    )]
    async fn self_service_portal_requests(
        &self,
        Parameters(args): Parameters<WorkflowArgs>,
    ) -> Vec<PromptMessage> {
        let body = format!(
            "{}{}{}\n{}",
            catalog_check_block(
                self.api_version(),
                &["incident-4.2.6", "change-1.4.0", "reservations-2.0.0"],
            ),
            render_context_header(args.context.as_deref()),
            include_str!("content/self_service_portal_requests.md"),
            delegation_guidance(),
        );
        vec![PromptMessage::new_text(Role::User, body)]
    }
}
